### ISSUE TITLE
behemoth ring desynthesis

### ISSUE THREAD

**Issue by whb07** [myera/issues#10]
behemoth ring should be desynthable as per wiki: 

http://ffxiclopedia.wikia.com/wiki/Behemoth_Ring

Desynthesis Recipes
Bonecraft (89/100)
Yield: Behemoth Horn x 1
Lightning Crystal
1 x Behemoth Ring

**Comment by MarkWaldron** [comment]
https://github.com/DarkstarProject/darkstar/pull/3192

**Comment by Locodawg** [comment]
This has been resolved.
