### ISSUE TITLE
Corsair Phantom Rolls - Unable to use Job Ability

### ISSUE THREAD

**Issue by Myronnis** [myera/issues#100]
Since update Phantom roll doesn't work at all, Macros / Job abilities menu, every time I try to roll something it just says "unable to use ability."

**Comment by Aerixaa** [comment]
Already made a ticket....

**Comment by Myronnis** [comment]
Yeah Majii told me you didn't, should have checked before posting it

**Comment by eraffxi** [comment]
fixed
