### ISSUE TITLE
Mamool Ja ACC issues

### ISSUE THREAD

**Issue by DeeJayMhyst** [myera/issues#104]
Have tried to solo a couple of Mamool Ja Pikemen using RDM/NIN. I've had no issue soloing these in the past, but now they double-attack relentlessly and their ACC is insane. They shred shadows fast, slow II seems to have less effect, and they are way harder than they've ever been. Camp is the Mamool Ja Staging Point in Bhaflau Thickets.

**Comment by Sanlord** [comment]
Heartfully Agree with this.

**Comment by benfolka** [comment]
i dont even get damage from other VT mobs but Mamool Ja Pikemen kill me

**Comment by GM-Dave** [comment]
There was a known issue with multi attack traits procing nearly 100% o mobs that had them. The issue should mostly be resolved. As for the "Accuracy issues" far as I can see now they seem to be working 100% as intended. Make sure you do not leave them up with their buff ability called "Warm -Up" as it provides the Mamool with a powerful EVA & ACC buff that needs to be dispelled.
