### ISSUE TITLE
Matt Glitched

### ISSUE THREAD

**Issue by Shahuaforthewin** [myera/issues#105]
After killing matt it black screens and no cut scene, I have two characters that need to kill Matt but can't.
Stuck @ level 70.

I have killed Matt several times now, and wasted items, so a little disappointing.

**Comment by Sanlord** [comment]
Yeah, that's pretty frustrating Maat is kinda meh nowdays....

**Comment by eraffxi** [comment]
this is an active area for dsp at the moment, they are working on it. it sounds like it's 100% consistent

**Comment by GM-Dave** [comment]
A recent patch has fixed the Maat fights. They should be working 100% now.
