### ISSUE TITLE
Dynamis-Jueno - killing goblin statue causes server crash

### ISSUE THREAD

**Issue by FleabittenGrey** [myera/issues#108]
We have tested this two times now.  When killing the goblin golem in Dynamis-Jueno, it causes the server to crash. (4001 error) Attached
![goblincrash1](https://cloud.githubusercontent.com/assets/18109825/15310551/95aad09e-1bb6-11e6-9738-034831b71500.jpg)
![goblincrash2](https://cloud.githubusercontent.com/assets/18109825/15310550/95aaa646-1bb6-11e6-8abc-fe103e81baaa.jpg)

 are two screenshots showing the r0 as the goblin thing dies.

**Comment by Locodawg** [comment]
This has been resolved.
