### ISSUE TITLE
Missing desynth

### ISSUE THREAD

**Issue by bigcarl35** [myera/issues#109]
Just an FYI.  In retail you can desynthesize Gavial Mail which really helps when you're trying to cap bonecrafting.  This desynth is missing on era.  Lightning crystal + gavial mail -> Sheep Leather, HQ1: High Quality Pugil Scales x2, HQ2: Rainbow Thread, HQ3: Titanictus Shell x 2.

**Comment by MarkWaldron** [comment]
https://github.com/DarkstarProject/darkstar/pull/3192

**Comment by Locodawg** [comment]
http://ffera.com/forums/recipes.php?id=3738

This has been resolved.
