### ISSUE TITLE
Sky mob Sprinkler imumm to magic dmg

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#11]
I was wait in sky for friends so i told myself let kill so Sprinkler in mean time. Found out that u cant do any magic dmg to them. 
My BLM hase caped skill caped merits and maxed out gear(http://www.ffxiah.com/item-sets/341939).

http://i.imgur.com/LT8zlKx.png

**Comment by Scavenge** [comment]
http://ffxiclopedia.wikia.com/wiki/Category:Magic_Pots

"Not only are these pots able to cast magic, but they possess a very strong defense to magic as well, and at times seem almost immune."

is there any way you can show that this is something more than what wiki is referencing?

**Comment by Aerixaa** [comment]
I dont know what u want. I showed u my gear i got caped INT merits caped element magic. it a lvl 73-76 mob and he resist not 1 spell he resist 4. But i could aspir and drain him easy... still dont understand what u want. I kill this mobs so many time for years on Retail when i did sky waiting for ppl. And ppl had bad gear no merits sure the got some resist but x4 0 dmg that not normal -.-.

**Comment by Miscbox** [comment]
Yeah I went up just now and they are completely immune to elemental magic. If it was just resistance then blm enfeebs would also have trouble which I had non in landing. Every single nuke I attempted did 0 damage lol.

**Comment by Scavenge** [comment]
this may be due to a dsp choice, i'll ask

**Comment by Locodawg** [comment]
Tested, working fine now.
