### ISSUE TITLE
Mangled Cock Skin Issue.

### ISSUE THREAD

**Issue by Sanlord** [myera/issues#114]
[http://ffera.com/forums/items.php?item=3083](url)
It's really missing on drop lists: Image Below:
![m c skin](https://cloud.githubusercontent.com/assets/15907792/15444727/212295a6-1eca-11e6-81d0-33a31b090973.png)

**Comment by Locodawg** [comment]
This has been restored.

**Comment by Sanlord** [comment]
Thanks for closing :) was busy irl :)
