### ISSUE TITLE
PM 4-2 Did not work

### ISSUE THREAD

**Issue by Ablonn** [myera/issues#115]
I and my team killed Ouryu, the title was changed but to talk to Justinius in Tavnazian, nothing happened.

After the fight, we had black screen and Loco took on her. trying to Justinus and nothing happened.
![ouryu 20-05](https://cloud.githubusercontent.com/assets/18625002/15445872/0818dd10-1ee1-11e6-934d-e4dc61de7ba3.png)

**Comment by Locodawg** [comment]
This has been resolved.
