### ISSUE TITLE
Rank listing not updating on website

### ISSUE THREAD

**Issue by bigcarl35** [myera/issues#118]
I've noticed that the rank listing of the players on the website has been unchanging the last couple of months, so I looked deeper to see what was what.  If you go to the summary rank page for a player and tally the points listed the overall amount looks right, but if you go to a specific breakout page, you'll see that the totaled points for the breakout is not the same as the point in the summary page.  If you want an example, look up the point breakdown for Paiine.  http://ffera.com/forums/ranks.php?define=40181  I've been leveling up my crafting lately.  The overview page says my crafting score is 325, but if you look into the crafting breakout page, my crafting score is 343.  http://ffera.com/forums/ranks.php?crafts=40181  This "difference" is apparent in the other breakout lists too.  I know this is probably a low priority but I doubt it would be hard to fix.

**Comment by Rihce** [comment]
should be updated now
