### ISSUE TITLE
Home Point in Misaeraux Coast not registering

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#120]
It seems like the Home Point #1 in Misareaux Coast (G-5) does not register. I have unlocked and used it twice so far, but when I am at a different HP it does not show up in the list, so I cannot warp to it, only away from it. Supposed to be under Tavanzian Archipelago along with Riverne - Site #A01 and Riverne - Site #B01.

Might be under Windurst Region now, because if you selct Travel to another homepoint > current region it shows the 4 areas of Windurst.

**Comment by GM-Dave** [comment]
Along with the Qufim Island HP, this is a Home Point that was implemented for the Rhapsodies of Vanadiel expansion in retail. There are currently no plans to implement these home Points for general use
