### ISSUE TITLE
Tinnin bug unable to move after Draw in

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#121]
When our LS did some ZNM after the latest server update, we discovered a bug with Tinnin. Sometimes after he used draw in on a character, that character would be stuck in the ground or in the air (?), unable to move, similar to bind and a circular area around the character would not be visible on the screen any more. Here are 2 screenshots, to show it from 2 different camera angles. GMs said this was a known issue but I thought the screenshots might help to show what happens.

![img_20160518_175936](https://cloud.githubusercontent.com/assets/18585931/15478825/16da20dc-211d-11e6-89bc-273dae49361b.png)
![img_20160518_175948](https://cloud.githubusercontent.com/assets/18585931/15478824/16d8e10e-211d-11e6-8d65-87b9c03a01d8.png)

**Comment by GM-Dave** [comment]
Unfortunately this is an issue with Draw In itself and not just a particular NM. Attempts at fixes have been made but never is guaranteed. Best course of action would be to limit the amount of times drawn in and try to watch the distance, position & location from which you are Draw In (I.E. Try to stay as reasonably close to the mob as possible and watch being Draw In when on/next to hills and cliffs.)

Sorry for the Inconvenience.
