### ISSUE TITLE
Rng Issus 

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#123]
Hey everyone, 

Well we all know that RNG ws not hiting. But the 2 ability which are not working Snapshot and Rapid Shot. Rapid Shot equiped also not working. I think that ability not coded or somethingh. Snapshot try Yoshi on RNG/NIN and SAM/NIN both jobs have same delay, which shows that Snapshot also not working.

**Comment by Rihce** [comment]
WS's are actually fixed. I will study what's wrong with Snapshot and Rapid Shot.

**Comment by eraffxi** [comment]
are both of these random chance to go off?

**Comment by Aerixaa** [comment]
Job Trait Overview

    Game Description: Occasionally reduces ranged attack delay.
    Job Traits are always active.
    Further Notes:
        Occasionally causes a ranged attack to fire instantly.

**Comment by GM-Dave** [comment]
Snapshot is essentially "Haste for Ranged Attacks", or in other words reduces the delay on ranged attacks. I believe this currently works.

Rapidshot is essentially a(n) X% chance to entirely ignore Ranged delay and go off instantly. Far as I know this hasn't worked for quite some time.
