### ISSUE TITLE
Can't trade

### ISSUE THREAD

**Issue by bigcarl35** [myera/issues#124]
This is an annoying bug, but there is a work around.  If you're crafting something and you want to trade the leftover mats, you need to zone first before you can actually trade them.  It's as if the leftover mats are locked in your inventory.  They're not grayed out, you just can't trade them till you zone.

**Comment by GM-Dave** [comment]
This is a know issue with trading that extends beyond crafting (has to do with items being in use by the player in some way.

Another work around is to have both parties involved in the trade click on a NPC and try trading again.

Unfortunately while annoying trading still works and a fix beyond this isn't known and isn't considered a priority issue. sorry for the inconvenience.
