### ISSUE TITLE
Castle Oztroja (S) zoneline is broken

### ISSUE THREAD

**Issue by Leif-Vivian** [myera/issues#125]
It is currently impossible to enter Castle Oztroja (S) because the door that you need to open is impossible to open even with master key.  
![img_20160526_040610](https://cloud.githubusercontent.com/assets/17759410/15569864/dadd9b44-22f8-11e6-9531-d025fcc0b1c7.png)

**Comment by RoahZoe** [comment]
this zone has been disabled because mobs in the zone have 0 hp
