### ISSUE TITLE
NM Buarainech exists but has no loot table.

### ISSUE THREAD

**Issue by Leif-Vivian** [myera/issues#131]
Went after this nm the other day to try for a pair of shrewd pumps and found out that he is functioning but appears to be missing a loot table.  

![ss 2016-05-28 at 07 30 00](https://cloud.githubusercontent.com/assets/17759410/15627332/62125178-24a6-11e6-9627-c57e3a0a100b.png)

**Comment by GM-Dave** [comment]
NM/content past CoP is still under development and anything past toAU is considered currently nonpriority issue, as it is content not currently being worked on.  If you think it should be possibly implemented as custom content, feel free to post on our forums about in the "suggestions" subforum. closing this ticket regardless
