### ISSUE TITLE
Magic Spell Range Incorrect

### ISSUE THREAD

**Issue by DeeJayMhyst** [myera/issues#132]
Current spell attack range (BLM) is ~20.3' however the correct distance is 21.8.

See: http://ffxiclopedia.wikia.com/wiki/Distance

**Comment by GM-Dave** [comment]
This is working as intended. This is how casting distance is configured for Era, both players AND MOBS. Otherwise Mob casting would be as long range as nearly ~30 yalms is configured for current retail.
