### ISSUE TITLE
Persistent Assault related Staging Point Bug

### ISSUE THREAD

**Issue by Armikazie** [myera/issues#133]
Hello! 

First I should explain what/how this happened to me in as much detail as possible.

It involves my character (Aias)

This occurred more than 2yrs ago now (I have been away for almost one and a half years). Just after everyone had their staging points wiped, I went about the task of getting them back. Random had given us the "all-clear". My ToAU mission 3 was reset. (The one needed for staging point access). While I was doing that, after I had gotten the Ilrusi Atoll Staging point, I accessed an assault mission npc and "accidentaly" excepted the Golden Salvage assault...  Silly me right? I'm a curious George, I know...

So every-time thereafter I attempted to acquire a staging point, none of them were saved to my list. (I am able to pass through from the staging point to Whitegate) I have checked all the staging point npc's before using the warp and so on, and have tried multiple times on every staging point since then. The only option open for me is Ilrusi Atoll. So of course I have to walk to all the hnms... (Khimira/Cerberus etc)

Both Choochoo and Random have had a look but even after removing the Key Item "Ilrusi Assault Orders" I am still stuck with just the Ilrusi Atoll staging point. No one had gotten back to me about it so Ive been trying to get by without...

Thx for your help

Aias

**Comment by Aerixaa** [comment]
I had that bug to just need to go ID assault NPC and say u give up that assault. he give u back a ID tag and u not stucked anymore

**Comment by Armikazie** [comment]
I didn't have the option then, and I still don't have it now.

**Comment by LocoFFEra** [comment]
This has been resolved.
