### ISSUE TITLE
Masterkey Acquisition 

### ISSUE THREAD

**Issue by Armikazie** [myera/issues#135]
Hello, Aias here!
A group of us did Bastok mission 2-3 last night and we were told by [GM]Loco that we would have to make a ticket in order to recieve the Masterkey.

Here are some screenshots as proof:

<a href="http://imgur.com/ENDst1W"><img src="http://i.imgur.com/ENDst1W.png" title="source: imgur.com" /></a>

<a href="http://imgur.com/iBdmT6L"><img src="http://i.imgur.com/iBdmT6L.png" title="source: imgur.com" /></a>

**Comment by Locodawg** [comment]
I got this one covered. 

So far Aias has been awarded Masterkey, will contact others as I see them online.

**Comment by RoahZoe** [comment]
next time submit a ticket like this to ffera.com/tickets please
