### ISSUE TITLE
Retrace!!! not working anymore

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#14]
Retrace not working anymore.

http://i.imgur.com/POT1iVN.jpg

**Comment by Scavenge** [comment]
the odd part is that the game already has a specific message for this, so its not necessarily a glitch, but the message might be firing off for the wrong reasons.  can you confirm that this is still an issue?

**Comment by Minnaa** [comment]
As of today, I can confirm that this is still an issue.

http://imgur.com/9pl0S7D

**Comment by Locodawg** [comment]
As of today, this still does not work.

**Comment by GM-Dave** [comment]
Considering you cannot progress through WotG missions past the very first one to unlock maws & the Pure White Feather keyitem (let alone begin and/or complete any nation specific questlines) This is a non-issue and not priority. This is something to wait on until WotG starts to rightly be worked on & coded.

In the meantime all Maws outside Jeuno as well East Ronfaure and Jugner are operational and usable w/o needing any missions progress. Additionally Home points in each of the 3 nations in the past are functioning.
