### ISSUE TITLE
Can't use a character name but it says that it's not taken on the character tool.

### ISSUE THREAD

**Issue by Ayalla** [myera/issues#140]
I have copied my data folder over and made another character already, but I can't make a character named Ayalla.  It throws an error, but I had checked prior to character creation to see if it was taken.

**Comment by LocoFFEra** [comment]
Hey Ayalla,

For future reference tickets like this one should be posted here instead http://ffera.com/tickets/.

With that said, I can confirm the name is available, could I ask what specific error you're getting when trying to create the character. Another thing you may want to try is to copy over your "data" folder from:

PlayOnline\SquareEnix\PlayOnlineViewer

and paste it into 

D:\Games\PlayOnline\SquareEnix\FINAL FANTASY XI

Copying the whole data folder from the first location to the second fixes a lot of character creation issues.

**Comment by Ayalla** [comment]
As I said in my post, my data folder is already copied over and I had copied it again when I got the name error.

I'm just getting an error with a ton of Japanese characters.
