### ISSUE TITLE
5-1 Fei'Yin Battle

### ISSUE THREAD

**Issue by Tacien** [myera/issues#142]
After completing 5-1 we received the cutscene indicating a win but did not receive the Key Item after exiting (Burnt Seal). This was for Milklady and Aule.

![img_20160605_204610](https://cloud.githubusercontent.com/assets/18506829/15809983/2a461ca6-2b5f-11e6-9fb6-f61baafe2572.png)

**Comment by LocoFFEra** [comment]
Judaine has sorted this issue.
