### ISSUE TITLE
Equipment affected by day/weather has no modifier

### ISSUE THREAD

**Issue by Leif-Vivian** [myera/issues#143]
It appears that that the modifier doesn't exist for items such as sorcerer's tonban and the elemental obis. 
Sorcerer's Tonban:
![sorcerer s tonban](https://cloud.githubusercontent.com/assets/17759410/15857631/f6ecc1ce-2c81-11e6-9197-7b4811eb2c6f.png)

Hyorin Obi:
![hyorin obi](https://cloud.githubusercontent.com/assets/17759410/15857641/06f5cbe2-2c82-11e6-9d01-9e983e1ee83d.png)

**Comment by Aerixaa** [comment]
Obi working for me even mod not showing on database. 286 in CT on lizzard with thunder 333 with obi on both trys i had Thunderstorm on. Same test again with THunder 4 with obi 1777 without 1662.

With Hyorin obi 297 Blizzard without 280 and Hailstorm up all time.

Well got 3 other belts also try with them all working i think mod is just not showing on database. well BLM pants i dont know never tested.

**Comment by Leif-Vivian** [comment]
Thanks for the reply! I was able to get my first obi tonight and did a little testing and it does appear to be increasing damage, which is in line with your testing as well. More testing needed to verify if sorcerer's tonban is currently working correctly but gonna go ahead and close this one.
