### ISSUE TITLE
Jacaranda Lumber synth has 2 different crafting synth lvls.

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#144]
I noticed something while crafting.
Jacaranda Lumber is usually a lvl 103 Woodworking synth.
http://ffxiclopedia.wikia.com/wiki/Jacaranda_Lumber

I skilled up on this synth but at 101 the skillups stopped. I had a look in the database to see if the lvl cap was different on Era and found two seperate entries for this synth. One seems to be capped at lvl 101 and the other at 103.
Jacaranda Log has the item-ID 2534 in the database and Jacaranda Lumber the item-ID 2535.

Keep up the good work! <3

**Comment by RoahZoe** [comment]
included fix in pull request to dsp https://github.com/DarkstarProject/darkstar/pull/3219
