### ISSUE TITLE
RSE NMs not dropping Key Items

### ISSUE THREAD

**Issue by monsieurwpayne** [myera/issues#146]
Killed Da'Dha Hundredmask in Beadeaux but didn't get the KI to trade in for Hume RSE.

**Comment by LocoFFEra** [comment]
Hey Monsieurwpayne,

Could you give me your in-game name and I can help baid-aid fix this issue until Warp implements a fix.

**Comment by monsieurwpayne** [comment]
Ah, right, how silly of me. In Game name: Aeyela.

**Comment by LocoFFEra** [comment]
This has been sorted.

**Comment by monsieurwpayne** [comment]
Posting this on behalf of my girlfriend, character name Kalcia. We just killed Leech King after tonight's reset and unfortunately she didn't get her Tarutaru Claim Slip either.
