### ISSUE TITLE
Limbus is broken (still). Chest drops going to random players outside of Limbus.

### ISSUE THREAD

**Issue by Judaine** [myera/issues#147]
Around 12:00PM EST on Thursday, June 9th, I received a tell from player Aeyela saying that she received a message while standing around in Southern San d'Oria saying she obtained items. She also was receiving "Time Remaining: (x:xx)" messages, while not in a battlefield of any kind. I warped to Aeyela, and I also began receiving those messages. I have noticed in the past that I would also randomly receive the "Time Remaining" messages, but did not think anything of it.
Aeyela also said that she has had problems with trying to zone out of San d'Oria zones, where sometimes when she goes to the zone line, it will zone her back into the same zone in a different position. I've heard this issue from a few players, and I've also experienced it a couple times.

Shiney sent me a tell saying that her group was in Limbus in East Tower Temenos, and that some chests they would open would not give them any loot, and would sometimes DC them. Then I got tells from Lemonskunk saying he received random items as well, while he was out in Qufim Island exping. A couple other people in his party also received some random items: Salohcin and Altracato. 
All players that received items from outside of limbus were asked to drop all of the items and take a screenshot for evidence, and I checked their inventories.

It would appear that players outside of Limbus that are in a party (not in the same party as people in Limbus, but ANY party), can potentially receive loot from chests in Limbus. This would also explain the "Time Remaining" messages, and the buggy zoning. 
Players were informed with a server message that Limbus is off-limits until further notice.

Below are screenshots of my chat logs with the players.:

![img_20160609_115114](https://cloud.githubusercontent.com/assets/19351709/15937917/d373ac4e-2e3e-11e6-92ba-7fecdb965ed3.png)
![img_20160609_115603](https://cloud.githubusercontent.com/assets/19351709/15937921/d39f69c4-2e3e-11e6-9c1b-93e81f7c7307.png)
![img_20160609_115930](https://cloud.githubusercontent.com/assets/19351709/15937919/d3786f0e-2e3e-11e6-8cda-c153bc467402.png)
![img_20160609_123336](https://cloud.githubusercontent.com/assets/19351709/15937918/d375dece-2e3e-11e6-9210-d33a62a2d959.png)
![img_20160609_123350](https://cloud.githubusercontent.com/assets/19351709/15937920/d38347a8-2e3e-11e6-93ea-0555082fa4db.png)

**Comment by GM-Dave** [comment]
This issue was resolved with Limbus being repaired in its entirety.
