### ISSUE TITLE
Chasing_Quotas DRG AF2

### ISSUE THREAD

**Issue by mathantolous** [myera/issues#148]
following the guide here for the DRG AF legs: http://ffxiclopedia.wikia.com/wiki/Chasing_Quotas

When I got to Esca the NPC was named Gachemage.
In the CS the NPC does not show up

 When I engaged in the conversation it said Esca and it went until the line after the prompt that asked if you knew what it was that was stolen: I chose the option of "I have a good idea"  the reply was "thats right, ...." then I was frozen in place

Trying the other option froze in same place using @release froze camera in place but got NPC to say Armor is buried on an island in battalia downs

**Comment by mathantolous** [comment]
I was able to complete the quest. After getting the armor is buried message I used a warp scroll and proceeded to try to complete the quest. Tiger NM spawned ok and I received the KI.

**Comment by RoahZoe** [comment]
the names seems to have been switched for Esca(NPCID:17187524) and Gachemage (NPCID:17187525) causing the cs not to work correctly
