### ISSUE TITLE
Trick Attack does not work with Skillchain Damage

### ISSUE THREAD

**Issue by neosatus** [myera/issues#149]
From Blue Gartr Wiki for Trick Attack: "The Enmity generated by your next attack (or Weapon Skill and potential Skillchain) is transferred to a player in front of you."

We've been doing a lot of Like The Wind lately and noticed something weird going on. We'll open the fight with my SAM aggroing and doing Konzen > Gekko for Darkness 1. We'll then have our Mandau THF close the chain with SATA Mercy Stroke onto our tank for Darkness 2. This causes the Mercy Stroke to hit for around 3k and the Darkness 2 to hit for over 4k. The fact that it hits so hard means the bonus damage from Trick Attack is being applied, i.e. it found a valid TA target (otherwise it wouldn't apply the damage, per the code). In every case, however, the THF ends up with aggro. I expected this was because the Skillchain damage was not being applied to the Trick Attack target as it should. I inspected the DSP code and verified this was true (battleutils.cpp line 3244, no condition to apply the enmity to TAchar instead).

I tried to come up with a quick fix but by the time this method runs the Trick Attack status effect will have been removed so the only way to know the skillchain was generated by a Trick Attack would be to pass the TAchar variable down the line (or add it to the WeaponSkillState?). I'll try to look into this more later and edit this comment.

**Comment by vampirexhunter** [comment]
This has been an issue for a long time.. only the initial WS dmg is transfered with TA, but the SC won't. Doing a LV2+ darkness SC for a THF will get him killed or will be tanking for a good while until the tank can regain it.. and seeing also that the enmity has been bugged for a while now... any tanks will feel useless.... We had one of our best BLM casting stone 1 during a KB fight, and still pulled hate...

**Comment by neosatus** [comment]
Well, on this server a well geared BLM spamming T1 nukes will do more DPS than many melee classes thanks to the low recast and cast time. They can also do it forever with a Moogle Refresh.

The thing about enmity that I don't understand and maybe someone with better know how can respond but in the code Enmity is capped at 10,000 CE and 10,000 VE. That seems really low to me but I assume the cap is there for a reason. Do enmity values over 10,000 cause some issue with memory or performance? I think that is the cause for a lot of issues people see because BLM's hit the Enmity cap along side the tank and the next time the tank takes damage he loses a little bit of Enmity, making the BLM top of the list until he takes damage. Since good BLMs generally have Blink or Utsu up this can make it hard for the tank to get aggro back and the BLM becomes a kiter.

If it's possible to increase that cap without issue and the TA/Skillchain bug could be fixed, I think Enmity would feel a lot better.

I've spent a lot of time pouring over the enmity code myself trying to understand it.

**Comment by neosatus** [comment]
Stack trace of the WS to SC method flow:

The TAchar is discovered in doPhysicalWeaponskill on line 56 and needs to be passed down the line somehow:

OnWeaponSkillFinished (charentity.cpp:801) calls onUseWeaponskill (luautils.cpp:3086) which calls onUseWeaponskill (mercy_stroke.lua:19) which calls doPhysicalWeaponskill (weaponskills.lua:18) which calls takeWeaponskillDamage (weaponskills.lua:884) then values get returned all the way back up to OnWeaponSkillFinished which a handful of lines later calls TakeSkillchainDamage (battleutils.cpp:3176).

I think I figured it out! However, the way taChar is defined and passed around is unclear to me so some tweaking is possibly needed but in general this path should work:

weaponskills.lua:228
`return finaldmg, criticalHit, tpHitsLanded, extraHitsLanded, taChar;`

mercy_stroke.lua:35
`local damage, criticalHit, tpHits, extraHits, taChar = doPhysicalWeaponskill(player, target, wsID, params, tp, primary);`

mercy_stroke.lua:42
`return taChar, tpHits, extraHits, criticalHit, damage;`

luautils.cpp:3121 (new line here) (this is probably wrong)
`CBattleEntity* taChar = lua_touserdata(LuaHandle, -5);`

luautils.cpp:3138 (was 3137)
`return std::make_tuple(dmg, tpHitsLanded, extraHitsLanded, taChar);`

charentity.cpp:732
`std::tie(damage, tpHitsLanded, extraHitsLanded, taChar) = luautils::OnUseWeaponSkill(this, PTarget, PWeaponSkill, tp, primary, action);`

charentity.cpp:801
`actionTarget.addEffectParam = battleutils::TakeSkillchainDamage(this, PBattleTarget, damage, taChar);`

battleutils:3176
`int32 TakeSkillchainDamage(CBattleEntity* PAttacker, CBattleEntity* PDefender, int32 lastSkillDamage, CBattleEntity* taChar)`

battleutils:3244-3251
`if (taChar != nullptr)` 
`{`
`    ((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(taChar, (uint16)damage);`
`}`
`else`
`{`
`    ((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(PAttacker, (uint16)damage);`
`}`

**Comment by Darkstorm87** [comment]
I wonder if it'd be possible to add a taChar property to the weaponskill state, and then pass the state down?

You'd only need to pass the state down to
`doPhysicalWeaponskill(attacker, target, wsID, params, tp, primary)`

If you have a valid taChar you'd need some mechanism of setting the property on the weaponskill state.  Might be able to do this with a luautlil?

And then you should have access to pass the taChar into TakeSkillchainDamage. When you get back to OnWeaponSkillFinished.

Similar steps, but perhaps a few less times you'll have to pass something around.

**Comment by neosatus** [comment]
Here's an easy way to fix the problem, however, the function getAvailableTrickAttackChar is now called twice per weaponskill. The work around for this would be to pass it down the chain of methods which would include modifying every single weaponskill script. I don't imagine anyone is interested in doing that. This fix will take 5 minutes to implement and it works. If it causes issues, you could revert it or do it the hard way, either one. I don't think it'll cause any issues and it helps enmity in coordinated groups a lot. Here's the fix:

**/src/map/entities/mobentity.cpp:748**
```
if (effect != SUBEFFECT_NONE)
{
    int32 skillChainDamage = battleutils::TakeSkillchainDamage(this, PTarget, target.param, NULL);
```

**/src/map/entities/charentity.cpp:631**
```
if (effect != SUBEFFECT_NONE)
{
    uint16 skillChainDamage = battleutils::TakeSkillchainDamage(static_cast<CBattleEntity*>(this), PTarget, actionTarget.param, NULL);
```
**/src/map/entities/charentity.cpp:724**
```
uint16 tpHitsLanded;
uint16 extraHitsLanded;
int32 damage;
CBattleEntity* taChar = battleutils::getAvailableTrickAttackChar(this, PTarget);
```
**/src/map/entities/charentity.cpp:~800**
```
if (effect != SUBEFFECT_NONE)
{
    actionTarget.addEffectParam = battleutils::TakeSkillchainDamage(this, PBattleTarget, damage, taChar);
```
**/src/map/utils/battleutils.h:153**
```
int32				TakeSkillchainDamage(CBattleEntity* PAttacker, CBattleEntity* PDefender, int32 lastSkillDamage, CBattleEntity* taChar);
```
**/src/map/utils/battleutils.cpp:3176**
```
int32 TakeSkillchainDamage(CBattleEntity* PAttacker, CBattleEntity* PDefender, int32 lastSkillDamage, CBattleEntity* taChar)
```
**/src/map/utils/battleutils.cpp:3242**
```
case TYPE_MOB:
{
    if (taChar == nullptr)
    {
        ((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(PAttacker, (uint16)damage);
    }
    else
    {
        ((CMobEntity*)PDefender)->PEnmityContainer->UpdateEnmityFromDamage(taChar, (uint16)damage);
    }
}
break;
```

**Comment by Darkstorm87** [comment]
I'm not great with C++, so I don't even know if it's possible.  But can you create a property on CBattleEntity that would be some kind of pointer to the WeaponskillState?  Then add a taCharacter property to the WS state?

You could make it so it only calls that function once, and then set the taChar on the WS state, which is associate with the CBattleEntity, which is available inside doPhysicalWeaponskill via "attacker".

When the weaponskill is done, would the WSState get garbage collected? or Could we kill it so that the property on CBattleEntity will only ever point to active WSStates.

I don't know if any of that makes sense.  And probably wont be necessary if calling the getAvailableTrickAttackChar doesn't cause issues.

**Comment by LocoFFEra** [comment]
This should now be implemented onto Era.
