### ISSUE TITLE
PM8-3 When Angels Fall Crashing Server

### ISSUE THREAD

**Issue by Darkstorm87** [myera/issues#156]
Seems intermittent, but it appears to be crashing the server.  We've experienced odd thing happening while trying to enter the fight.

Twice it crashed the server immediately when someone checked the Transcendental Radiance.
Once it froze one of the characters outside of the fight.  They could not move or enter any commands other than log out.
Once it crashed one of the party members and would not let them join the fight.

**Comment by GM-Dave** [comment]
this should not be an issue anymore, If you by chance are still having issues with this please contact a GM in game or file a NEW ticket via the Era HelpDesk (Service Requests) on the main page
