### ISSUE TITLE
Low damage on critical hits.

### ISSUE THREAD

**Issue by AllisonHalsey** [myera/issues#159]
the damage on critical hits might be incorrect since they do the same amount of damage than regular melee hits. Here's some pictures of that:
[http://imgur.com/UIqhHyt](url)
[http://imgur.com/usbIP39](url)
[http://imgur.com/56pLONp](url)
I was using a Ragnarok (86  Base damage) and Chuchurocket a martial bhuj (88). Relic procs did about 440-450 damage.

**Comment by Acryptik** [comment]
I also believe critical hits to not be working properly as almost every single one I've landed since playing has had lower damage than regular melee hits.

**Comment by GM-Dave** [comment]
This issue has since been resolved. If any new issues pop up please file a new ticket.
