### ISSUE TITLE
Severe accuracy problems with PC vs monsters and vice versa

### ISSUE THREAD

**Issue by Miscbox** [myera/issues#16]
For the last week I have suspected that there are extreme problems with accuracy on the server. We had been informed that nothing has changed but unfortunately after this DL run we have some numbers and proof that things are off. 

First case scenario: JOL. A ninja/drk was able to tank the jailer and its adds for a good minute and a half without getting hit much, as BLMs being MISSED by the spawned adds consistently.
(Reference Jailer of Love code is off again. #12 Ticket by me.)

We attempted a Dynamis lord run and in parsing the accuracy after wiping with 2hr double madrigal this was the result: http://i.imgur.com/CXyVTqP.jpg

As you can see, with 2hr accuracy songs with Nightingale Troubadour, accuracy was nowhere near what it needed to be or what it should have been. The first two numbers with the highest accuracy, Anochrite and  Horsy were both playing on jobs using A+ weapons and using sushi (THF ano and SAM horsy) AND STILL DID NOT REACH ACCURACY CAP WITH DOUBLE SOUL VOICE MADRIGALS. 

Here is video evidence of us doing the run with the same setup, with no accuracy problems whatsoever, and nevermind the fact that this is the retail standard strategy.

https://www.youtube.com/watch?v=OkrRGwWrrEE

It does not make sense. This problem 100% applies to other mobs in the game, especially monsters that are high enough to activate level penalties. 

A+ Weapon (i.e. Dagger thf) with merits - 276 (292 with capped merits)
C- Weapon (i.e. KClub drk) - 220 (236 with merits)
Sushi (+15%) - 42acc to thf, 35acc to DRK
SV Madrigal - 76acc

THF - 410acc before gear, 88%(was that right?) with +36 acc in gear, so would need about 480acc total to hit 95%
DRK - 347acc before gear, would need +133acc in gear to hit 95% (ain't happening)

This change effectively gave Dynamis Lord approx. 25% more evasion than he used to have, which converts into an amount that's borderline impossible to hit even with the best gear available on the server.

If you need any more information hit me up on Izayoi! Thx!

**Comment by Aerixaa** [comment]
Well i remeber that on retail to get 95% acc u need  2 x madrigal with SV, cor rolls, gravity or dnc and food.

**Comment by Scavenge** [comment]
i added this fix recently: https://github.com/DarkstarProject/darkstar/issues/2767

does the issue still exist?

**Comment by PresidentNixon** [comment]
It seems to be a problem with weapon skill ratings, as a drk using scythe(zimaras) had capped accuracy but clubs are still hitting under half even with double SV madrigals and club merits

Today: http://i.imgur.com/Tbch34A.jpg

**Comment by Scavenge** [comment]
oddest thing about that photo is that evasion/'accuracy is coded to have a 95% hard cap i believe.  so whether you have 100% accuracy or evasion, you should still only succeed in your rolls 95% of the time

**Comment by Scavenge** [comment]
it may be related to 1hand vs 2hand weapons.  will need more testing to confirm that though

**Comment by PresidentNixon** [comment]
http://i.imgur.com/0N4WjM0.jpg

**Comment by Locodawg** [comment]
This has been resolved, it was due to a bug making all enemies 30% stronger.
