### ISSUE TITLE
Utsusemi can not be Cancelled/Removed

### ISSUE THREAD

**Issue by monsieurwpayne** [myera/issues#161]
The buff effect from either Utsusemi, Copy Image, can not be removed from the player.

I'm unable to remove either Ichi or Ni using both the Windower cancel plugin (cancel Copy Image*, which until this morning has been working without issue) nor by manually clicking the buff off the good ol' fashioned way with the game controls. 
- With manual removal, the Utsusemi icon disappears from my status bar but reappears a few moments later.
- In neither case am I receiving the "Copy Image effect wears off" log notice. 
- Being attacked by monsters lowers the shadow count as you'd expect. 
- Changing jobs also removed it.

To try and fix this, I have: changed jobs, relogged, restarted Windower, rebooted PC, still not working. I've conversed with others in TehSocial who are having the same problem as me, which leads me to believe it's a server problem. I looked at the packets Windower is sending and receiving but saw no anomalies.

As far as I know, every other buff is behaving normally.

In-game Name: Aeyela

**Comment by Aerixaa** [comment]
Also Ninja sub Ichi can overwrite NI which it should i think that also 1 think that show how utsu is messed up. R.I.P Ninja

**Comment by GM-Dave** [comment]
Utsusemi, regardless or tier or job status will overwrite itself. There should be no need to remove the status.
