### ISSUE TITLE
Zoning into same zone.

### ISSUE THREAD

**Issue by Taladric** [myera/issues#162]
This has been happening to me almost 1 of every 2 times I zone in the game.  I'm wasting Nexus capes and instant warp scrolls as well as trying to zone out of dynamis just to end up at zone and dying.  It's becoming very old and I don't understand why it's happening to me more than others.

**Comment by GM-Dave** [comment]
This was due to a server bug, which should be resolved now but may still happen on occasion. If it is something you are still having considerable issues with please file a new ticket.
