### ISSUE TITLE
Ice Spikes and Shock Spikes additional effects not working.

### ISSUE THREAD

**Issue by Vasage** [myera/issues#168]
Ice Spikes additional effect of Paralyze never procs when attacking a mob with the spell active. (Unsure if the effect is working when a mob attacks a player with this spell active)

Shock Spikes additional effect of Stun never procs when attacking a mob with the spell active. (Unsure if the effect is working when a mob attacks a player with this spell active)

**Comment by Aerixaa** [comment]
Yeah the effect donst proc on player to fight some Doom warlocks and taxim yesterday the all had Ice spike no para. Same last when i was blu spell hunting with friends Soulfyler Shock spikes dont stun. ALl spikes spell do a lot of dmg donst matter if u have magic dmg taken or DT gear or shell on always does same dmg. I saw that then we fight ZN2 T2 halvung path Dragon allways does 170 blaze spike dmg no matter what u had shell dt or mdt dosnt matter full dmg.

**Comment by GM-Dave** [comment]
This issue has long beeen since resolved with an update.
