### ISSUE TITLE
Lamina NM not spawning.

### ISSUE THREAD

**Issue by Vasage** [myera/issues#169]
Lamina is currently listed in the monster DB with a respawn time of 2 hours with spawn conditions set to Evening 18:00-06:00 in Rolanberry Fields (S). After several trips out there, spending more than 2 hours Lamina does not appear to be spawning at all.

Her counterpart NM, Hyakinthos spawns in Sauromogue Champagne(S) with no issues.

**Comment by LocoFFEra** [comment]
This has been resolved.
