### ISSUE TITLE
Ruby Quadav in Pashow Marshlands (S) checking Impossible to Gauge.

### ISSUE THREAD

**Issue by Vasage** [myera/issues#170]
Ruby Quadavs in Pashow Marchlands (S) are currently checking at "Impossible to Guage". In this zone, these are listed as standard mobs according to the Pashow Marshlands (S) Wiki page.

http://ffxiclopedia.wikia.com/wiki/Pashhow_Marshlands_(S)

**Comment by Aerixaa** [comment]
Know issus for years now and it because WoTG is not coded every NM in present  it past counter part check Impossible to guage aDaman quadavs yagudo high prist etc.

**Comment by GM-Dave** [comment]
This issue is non-priority, due to WotG expansion on being a focus. The monsters checking IG doesn't actually affect anything important and will likely be fixed once DSP actively beings working on WotG.
