### ISSUE TITLE
Ninja Kyahan hours innaccurate

### ISSUE THREAD

**Issue by monsieurwpayne** [myera/issues#171]
The movement plus from Ninja Kyahan kicks in and stops an hour later than intended. Instead of working from 6am - 6pm, they work from 7pm -7am. However, if I manually un-equip and re-equip them in the hour before (6pm - 7pm), the buff applies. It's like the automatic application of the buff is being delayed by an hour for whatever reason. Same goes for taking them off between 6am and 7am. The buff is removed. It's not an enormous deal since it stays on for the same duration, but you can get an extra hour out of them manually changing them at the start and leaving them on till the end.

**Comment by Aerixaa** [comment]
Well this old and know isuss mad a ticket over 1 year about this. And forgot to make a new one on github because +1 are working like the should from 17 to 7. ALsso if u zone u lose that extra 1 hour works only when u stay in 1 zone all the time. I guess that why the never fix it

**Comment by LocoFFEra** [comment]
I just fixed this, it'll be active on next server reset.
