### ISSUE TITLE
Saurian helm and Mirage Keffiyeh issues

### ISSUE THREAD

**Issue by hajuhl** [myera/issues#172]
The effects of these helmets are not affecting breath damage. Saurian helm does show the correct numbers, but it is not applying the damage. In Dynamis-Bastok, my Heat Breath does 1075 with Saurian and 960 with Relic Hat - both are doing different damage in log, but both are applying same damage in game (both are supposed to increase breath damage by 10%, but don't).

**Comment by LocoFFEra** [comment]
This has been resolved.
