### ISSUE TITLE
Trial size trials. SMN in general

### ISSUE THREAD

**Issue by Keiann** [myera/issues#173]
Trial size trials quests do not teleport you to the actual solo quest for the avatars. They teleported me to the high level party dungeon please fix this. dont want to always be depending on others to get my summons.

Summoner spirits dont seem to cast spells when engaged in battle. I've done some research and all post say that if summoner has capped their summoning magic skill the intervals of spells cast by spirits should be 45. Yet no spells were cast during the 2 minute fight. The spirit did not take any hits so it should not have been interrupted also did not use retreat or assault so timer was not reset!. Yeah avatars are way better but spirits are still part of the summoner class if this was intentional please change this it ruins a big part of this class.

Finally Avatars and spirits alike are supposed to attack anything that aggros their summoner again not sure if this was intentional if not please fix this

**Comment by GM-Dave** [comment]
All these issues have been rectified by recent updates.
