### ISSUE TITLE
Corsair still has issues

### ISSUE THREAD

**Issue by Myronnis** [myera/issues#174]
First I noticed I never rapid shot at all, it has been broken a long time, and I think Ranger too. added to that, the Ranged Delay seems doubled after shooting it says I have to wait longer to do this action, I have to wait delay between RA, and the Gun Delay is really slow also.

Second Issue I noticed is the Merit Ability Snake Eye not working fully, it only gives 1 no matter how many merits you added in, at 5 Merits I should be getting 50% of the time the right number to make it 11

For exemple i'm on a 8, I won't Double up because I need 1-2-3 to make 11, and 9 would be a bad roll for many rolls, so I just stand down, but if Snake eye was working i'd have 50% chance of getting a 3, which make the ability much better because all my JA reset after a 11

I play COR most of end game event and i've tried Snake Eye over 100 times already so theres is no way I never got the 50%

**Comment by neosatus** [comment]
I've definitely seen Rapid Shot kick in on my RNG.

**Comment by Myronnis** [comment]
well it definitely doesn't work on COR, Update I got a 2 with Snake eye just once, which makes me believe i have only 10% like if I had only 1 Merit in it, while I have 5 (only procs 10% of the time)
