### ISSUE TITLE
THF main and SA 

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#175]
Looks like when u SA + WS u dont genrate any hate it like u not on hate list at all and SATA is wrong any many was just check the code it messed up 

http://imgur.com/a/ozK1u

SA solo give hate and ws solo give also hate

Cannonball SA works also front 

On SATA only TA dmg is sticking

**Comment by LocoFFEra** [comment]
A fix has been implemented to fix SATA. It should be active on Era now.
