### ISSUE TITLE
Xzomit Organs not on Ul'xzomit loot table

### ISSUE THREAD

**Issue by FleabittenGrey** [myera/issues#176]
http://ffxiclopedia.wikia.com/wiki/Xzomit_Organ - this particular organ, on ERA, is only dropping off the Om Xzomit in Sea.  (See:  http://ffera.com/forums/items.php?item=1785)  If possible, can they please drop off the Ul'xzomit too, to be more 'retail accurate?'  Thank you for reading!

**Comment by GM-Dave** [comment]
The drop should be adjusted on the mobs to be more accurate. If this is still an issue please file a ticket via the Era HelpDesk (Service Requests) on the main page.
