### ISSUE TITLE
Dagger wielding Aern in Al'taieu wielding kraken clubs

### ISSUE THREAD

**Issue by Elaandri** [myera/issues#177]
I've fought them repeatedly and they're incredibly strong because they are using what appears to be the same calculation as a Kraken Club uses for attacks per round, and their attack damage is not reduced to reflect this insane number of possible attacks.

**Comment by GM-Dave** [comment]
This was due to an issue where mobs with multi-attack traits would proc the multi attacks on all hits. This has been since adjusted and made more manageable.
