### ISSUE TITLE
Experience gain with pet is too low (BST, possibly other pet jobs)

### ISSUE THREAD

**Issue by gmolsick** [myera/issues#188]
Noticed when soloing the past few days that my experience gain is lower than it should be when fighting with both charmed pets and jug pets. Experienced this with EP through VT mobs.

Also possibly related, possibly not: sometimes I would get no exp gain or kill credit at all for some kills, though I was unable to reproduce this with much consistency; though I can say it did not seem to be limited to instances where pet delivered final blow.

**Comment by GM-Dave** [comment]
Getting "kill credit" is more an issue to do with FoV then it is with job & pets or party size. If your not getting kill credit per page you need to reflag your FoV page. Additionally this is currently broken in favor of the player; Even if you do NOT get exp for the kill for w/e reason, so long as you WOULD it will still count towards the page most of the time.

As for the pet issue this seems to have been repaired by a recent update. Closing ticket.
