### ISSUE TITLE
Jailer of Prudence

### ISSUE THREAD

**Issue by Miscbox** [myera/issues#19]
When you kill Jailer of Prudence there's a chance that on the first pop both monsters will drop items. I assume this is a problem with a mob ID and the check system. It's probably randomly selecting mobs between the IDs that are duds vs true and in light of this people lose pops if they assume they should only get one drop per pop.

**Comment by GM-Dave** [comment]
I believe this was fixed with an update performed by warp some time ago. If there are still issues pelase file a new ticket.
