### ISSUE TITLE
Jailer of Justice

### ISSUE THREAD

**Issue by AllisonHalsey** [myera/issues#190]
The respawn timer of  Qn'xzomits on the fight is way lower than the one on retail, spawning 2  adds around every 10-12 seconds when it should be 1 around every 30 seconds. They are also able to use mijin gakure multiple times in rapid succession.

**Comment by eraffxi** [comment]
in retail they would mijin gakure and not die, unless you are saying they are spamming it really fast

**Comment by AllisonHalsey** [comment]
They would Mijin Gakure once the next add spawns if not killed, roughly around 20 seconds later.
