### ISSUE TITLE
attributes merit points shall be limited

### ISSUE THREAD

**Issue by benfolka** [myera/issues#192]
altough server limit is 10, 
merit limit shows 15 points so we are wasting alot of xp before finding it out. 
please either fix limit to be fair new players
or make limit 15 to be fair to who wasted points, which is for all players.

**Comment by Darkstorm87** [comment]
There's a ton that would go into limiting those attribute merits, and a good chunk of it is client side DAT modification which is not easy, and the Devs have said they will not do until Retail XI is done changing stuff.  It'd be a constant war to keep those modified DAT files in place.  On retail, Merits 11-15 do not go into effect until lvl80 anyway, so if you read any of the common knowledge wiki articles on merits, you'd know this.

I would recommend that they create some highly visible page on the forums or wiki that contains a thorough list of these types of things for new players.

**Comment by benfolka** [comment]
thanks for the reply. those limits are not client side legiondark has it at 5 limit, if i understood you right.

**Comment by Darkstorm87** [comment]
They could potentially make these changes in merits.cpp.

```
static uint8 upgrade[10][16] =
{
    {1,2,3,4,5,5,5,5,5,7},             // HP-MP
    {3,6,9,9,9,12,12,12,12,15},   // Attributes
.
.
.
```
```
static const MeritCategoryInfo_t meritCatInfo[] =
{
    {3,30,0},  //MCATEGORY_HP_MP
.
.
.
```

**Comment by Aerixaa** [comment]
Pointless tbh. We veteran need something where we can spend merits. It pointless to much work

**Comment by GM-Dave** [comment]
A solution for this is potentially being looked into, However it is not a priority issue, especially as there's merits that should work in general that just do not. 

Regardless players could also save themselves a lot of headache by simply asking questions or researching the issue before just dumping their merits before hand (it's been a known issue and is weel documented.) Closing this ticket for now.
