### ISSUE TITLE
Power Leveling has been broken for almost 5 months

### ISSUE THREAD

**Issue by Manticmage** [myera/issues#193]
Power Leveling has been broken for almost 5 months. First issue was opened on March 9th by me here: #27 , Another was opened by Mozzy4Ever here: #117 .

In short, if any outside member heals anyone in a party or any solo player, they will not get XP.
_This is a major issue and should be given priority over other trivial things._

No Devs or admins have commented on this issue. Can we have some insight on when it will be looked at?

Thank you.

**Comment by Manticmage** [comment]
Well I found an open issue on the Darkstar Forum pointing out this issue. I'd like to encourage everyone to go post there so perhaps this issue will be given priority:

[https://github.com/DarkstarProject/darkstar/issues/3002](https://github.com/DarkstarProject/darkstar/issues/3002)

**Comment by GM-Dave** [comment]
This has been fixed with a recent server update.
