### ISSUE TITLE
Blu burst affinity

### ISSUE THREAD

**Issue by dwn134** [myera/issues#195]
Currwntly not working. Can use ability and shows icon but cast a spell and effect doesnt trigger and icon doesnt go away either until it times out

**Comment by LocoFFEra** [comment]
Burst Affinity is coded on a spell to spell basis. I've got it working on the major spells at the moment, if there is a specific spell you want it working on lemme know and I'll see if I can add it to the specific script.

**Comment by dwn134** [comment]
Heat breath and frost breath

**Comment by LocoFFEra** [comment]
According to the official Wiki, neither of those are considered physical blue spells.

http://ffxiclopedia.wikia.com/wiki/Chain_Affinity

http://ffxiclopedia.wikia.com/wiki/Blue_Renkei

http://ffxiclopedia.wikia.com/wiki/Heat_Breath

http://ffxiclopedia.wikia.com/wiki/Frost_Breath

**Comment by dwn134** [comment]
They arent physical they are magical and supose to be able to use in a magic burst with burst affinity. Your thinking of chain affinity
