### ISSUE TITLE
Destroyers ( hand to hand weapon ) broken

### ISSUE THREAD

**Issue by benfolka** [myera/issues#198]
[Destroyers](http://ffxiclopedia.wikia.com/wiki/Destroyers) is 2nd best weapon for monk and it is broken.
The latent effect on it is what seems to be  not working. 
Could you fix it as soon as possible if it is an easy fix ?

**Comment by GM-Dave** [comment]
Unfortunately the WS points system seems to currently be broken. A fix and/or work around is in the works, and a general announcement will be made when the change/fix is implemented.

Sorry for the inconvenience
