### ISSUE TITLE
Light/Dark Arts As /SCH

### ISSUE THREAD

**Issue by Chuchu90** [myera/issues#200]
Currently not functioning as it did in retail. If your main job has the magic skill that would be boosted from Light/Dark arts you will receive B+ rating in said skill.

However, if your job does not have the skill, for example, White Mage does not have Dark Magic Skill, then you will not receive the B+ rating in skill while under Dark Arts.

**Comment by dwn134** [comment]
This has been resolved. If you could please close your ticket
