### ISSUE TITLE
Pet auto-engage.

### ISSUE THREAD

**Issue by Chuchu90** [myera/issues#202]
Before the big DSP update a couple months ago this functioned correctly. If the mob you were attacking had aggro on you, your pet would automatically re-engage without having too use Assault when re-summoned.

**Comment by CogEra** [comment]
On retail, if any mob is targeting a smn, and their pet is idle, it will auto-attack that mob.

**Comment by GM-Dave** [comment]
This has fixed. Summons now will a) engage mobs that have aggroed the player and b) attack mobs the player has engaged

Additionally Spirits will also cast spells once again.
