### ISSUE TITLE
Manually removing Utsusemi:Ichi or NI shadows cause the shadows remaining to come back.

### ISSUE THREAD

**Issue by Leif-Vivian** [myera/issues#203]
This bug would only affect main job Ninjas considering Utsusemi:Ichi shadows overwrite Utsusemi:Ni shadows from subjob.  However say for example you are on ninja main and you have 1 :Ni shadow remaining and you try to manually remove it to cast Utsusemi:Ichi it is going to give you the error message because it put your last remaining ni shadow back up on the hotbar instead of it being removed.
![img_20160808_152817](https://cloud.githubusercontent.com/assets/17759410/17495240/f2881a66-5d7d-11e6-8311-3ce45960c4c5.png)
![img_20160808_152818](https://cloud.githubusercontent.com/assets/17759410/17495259/12cd2ffa-5d7e-11e6-8d39-befd4a3aea43.png)
![img_20160808_152837](https://cloud.githubusercontent.com/assets/17759410/17495282/2a2d9d60-5d7e-11e6-9d18-a17871310cf0.png)

**Comment by GM-Dave** [comment]
This shouldnt be an issue anymore. Additionally Utsusemi overwrites itself regardless of job status (Nin mainn/sub) or tier (Ichi/Ni) via DSP/Era
