### ISSUE TITLE
Wivre and Mamool insanely hard needs to be adjusted

### ISSUE THREAD

**Issue by benfolka** [myera/issues#213]
I am not gonna be polite,
i dont know whichever superman wanna be little boy said wivre and mamool has to be harder after he got it but,
at the moment they are super super hard it is nonsense and stupid to keep it this way.

**Comment by eraffxi** [comment]
wivre are supposed to be hard, they are a combat alternative to an item that costs 10 million gil.  mamool on the other hand do not have any custom scripts.

**Comment by eraffxi** [comment]
if you want wivre materials there are lower level wivres that are not custom-scripted.

**Comment by benfolka** [comment]
and noone sells that item cause noone can kill it any more. and the drop rate is a stinking joke

**Comment by eraffxi** [comment]
then you can buy it. i'm not changing wivres. the item is infinitely available from the npc in lower jeuno.

**Comment by eraffxi** [comment]
in fact i'm going to make them even harder. suck it.

**Comment by benfolka** [comment]
your funny
