### ISSUE TITLE
Club WS MP restores not working

### ISSUE THREAD

**Issue by dwn134** [myera/issues#218]
when trying to use moon light  or starlight ws it targets yourself and says you cant be seen and wont use said skill

**Comment by KalinaERA** [comment]
This is also an issue with the Staves weapon skills.

**Comment by GM-Dave** [comment]
This is a known issue with staff & club restorative WSs. Unfortunately it is not a priority.

should this be fixed in the future, a announcement will be made. Until then am going to close the ticket
