### ISSUE TITLE
Dying in 2-3 Windy fight gave Master Key but no CS // Quest Progress

### ISSUE THREAD

**Issue by Khundes** [myera/issues#220]
I fought 2-3 Dragon in Balga Dais as a Bastokan, and I died in the fight, but we won anyway a few seconds after. I got the system message that Master Key was unlocked, but I had no button to return to home point, nor was I getting the cutscene.

I tested and went to next step in the quest and I couldn't progress, as if I hadn't won the fight.

**Comment by GM-Dave** [comment]
Closing ticket due to how long it has been since this was opened, and assuming its been resolved. If this is still an issue then please contact a GM in game and/or file a new ticket via "Service Requests" (HelpDesk) on the main page
