### ISSUE TITLE
COP 5-3 Where Messengers Gather (Ulmia's Path)

### ISSUE THREAD

**Issue by thorules** [myera/issues#222]
Got CS fro Port Sandy - go to Cathedral and he gives me message for cop 3-3.  So when I go to windy it wont give me CS so cannot proceed

**Comment by GM-Dave** [comment]
If you are still having issues with this mission, please contact a GM in game and/or file a new ticket via the Era HelpDesk (link "Service Requests" under Tickets from the main page)
