### ISSUE TITLE
If a consumable item is cancelled due to resting, it becomes unusable until zoning.

### ISSUE THREAD

**Issue by Doroplet** [myera/issues#225]
An "Unable to use item" message appears in chat. Then the casting time bar goes up, and nothing happens. The item also can't be moved between bags. Tested with food, Instant Warp, scrolls, and echo drops.

**Comment by GM-Dave** [comment]
This has been a known issue for quite some time, and is a issue with the server core (DSP code). Unfortunately it isn't a priority issue, but I know it is being looked into. At the least there are work arounds for it besides zoning (logging/force dcing a char will also fix the problem.)

Am closing the ticket for now. If the issue ever gets completely resolved, there will be a general announcement made along with any other updates made.
