### ISSUE TITLE
bcnm under observation

### ISSUE THREAD

**Issue by yaajxyooj** [myera/issues#228]
I did BCNM 40 and traded my orb around 5:30 pm mountain time and died, but Yaaj and Demolition defeated the BCNM.  Afterwards when trying to do it with their Star Orbs, it showed that it was already used when it wasn't.

**Comment by GM-Dave** [comment]
This issue has been resolved via a duplicate ticket on Era HelpDesk. For issues such as these (Item Redemption/R0's) please use the Helpdesk (Service Requests link from the main page).
