### ISSUE TITLE
Evoker's Roll - Incorrect Amount

### ISSUE THREAD

**Issue by Logos12** [myera/issues#229]
Currently, Evoker's roll gives a refresh value that is -1 of what it should be. For example, if you roll a 1, 2, 3, or 4 you will get 0 mp/tic rather than 1. If you roll a lucky 5, you get 2 rather than 3, etc. Attached is a table for reference: 
![ss 2016-09-25 at 01 41 15](https://cloud.githubusercontent.com/assets/22434450/18818234/56584176-8329-11e6-810b-62d679de9289.png)

**Comment by GM-Dave** [comment]
This issue has been resolved, the roll repaired to function properly
