### ISSUE TITLE
Lost missions

### ISSUE THREAD

**Issue by Zhafire** [myera/issues#233]
Hi, last week i rush nation missions with a friend,to get dynamis and then sky acess,we have so much trouble to defeat shadow lord,cause the door was bugged,the gm Yoshi help us,we finish it and go rush zilart untill  11    The Hall of the Gods.

Well we log off,and today when we log to finishi sky acess all missions is gone,we bk to 5-1,but already rank 6,cant enter dynamis and all zilart mission is gone.

plz  get the missions bk.

the player name is Kyoshiro,but hedint speak english,then i make this ticket for him.

**Comment by Zhafire** [comment]
i got photos proving i'm rank 6 but nation mission is still on 5-1.

**Comment by GM-Dave** [comment]
There is a duplicate ticket on the Era HelpDesk, so please use that one to communicate if there are still issues.
