### ISSUE TITLE
Missing Chevral Salmon

### ISSUE THREAD

**Issue by bigcarl35** [myera/issues#236]
I've been leveling fishing and I needed a Salmon for my rank up mission.  I went to East Ronfeure and fished in the Chevral River and all I caught was shining trout.  I was using a mithran rod and fly lure/trout balls which is what you should use to catch trout and salmon.  Salmon is capped at 21.  I went from level 8 to 21 and only caught trout.  Any chance salmon are missing from their namesake river in East Ronfeure?  When I played retail I caught salmon in that river.  Just seems very unlikely that I could level that much there and not catch a single salmon.

**Comment by GM-Dave** [comment]
Era Fishing =/= Retail fishing. I'm not personally sure on how the fishing system works, outside of suggesting to attempt to use varying combinations of rods & lures/bait to get different fish.

I do know for a fact the Fish does exist. Try asking around to other fisherman in game they should be able to better assist you.

**Comment by bigcarl35** [comment]
I've discovered since opening this ticket that like the crafts, you don't need to do the hand ins for leveling, which is what I needed the salmon for.  So, it's not the show stopped I thought it was.  (I bought the salmon from the Fishing Guild in Selbina.)  So, now it's nothing more than an oddity.  Thx for responding though.
