### ISSUE TITLE
Desert boots movement speed

### ISSUE THREAD

**Issue by dwn134** [myera/issues#237]
Is not functioning with sch. Spell sandstorm. Not sure if works in real weather or not

**Comment by GM-Dave** [comment]
To be honest I'm not sure if the effect of desert boots was ever implemented to begin with. Someone with that knowledge or ability would be able to better comment.

**Comment by dwn134** [comment]
I got them from a fellow sch that now has gaiters and said that they did work before

**Comment by GMYasiinEra** [comment]
this is fixed. close please
