### ISSUE TITLE
Successfully stole from Maat on limit 5 quest and did not win fight - Please grant level cap at 75

### ISSUE THREAD

**Issue by JohnVPage** [myera/issues#238]
Had a successful steal on my first Maat fight to break level cap and it did not give me victory. Went back to Maat to try and trigger cut scene and he asks for testimonial again. Won't accept trade of testimonial or warp scroll to complete limit quest. Would like to have defect fixed and quest complete so I can level to 75. Submitted ticket per Soapytoast.

![steal](https://cloud.githubusercontent.com/assets/23156678/19840357/11787122-9eca-11e6-96af-99d30266a3b9.png)

**Comment by JohnVPage** [comment]
Game name is Deathdealerjax

**Comment by GM-Dave** [comment]
If you still need assistance with this, please contact a GM in game and reference this ticket to them
