### ISSUE TITLE
spells "Distract" and "Flurry" have no effect

### ISSUE THREAD

**Issue by nelenel** [myera/issues#239]
http://ffera.com/forums/items.php?item=4912
http://ffera.com/forums/items.php?item=5104
http://ffxiclopedia.wikia.com/wiki/Distract
http://ffxiclopedia.wikia.com/wiki/Flurry

tested in-game, the spells can be learned and cast, but they have no effect whatsoever on enemy or player.

**Comment by GM-Dave** [comment]
These spells were introduced post 75 cap, and were never intended for use on Era. That may change but in the mean time there or no immediate plans to implement their usability.
