### ISSUE TITLE
stole the warp scroll from Maat on limit 5 quest and did not win the fight - Please grant level cap at 75

### ISSUE THREAD

**Issue by fateraines** [myera/issues#240]
stole the warp scroll from Maat didn't give me the win, Please grant level cap of  75
![image](https://cloud.githubusercontent.com/assets/23178200/19873487/3eda2fd4-9f8d-11e6-9df9-7ce6e35bfeda.png)

in game name is Fate

**Comment by eraffxi** [comment]
closing
