### ISSUE TITLE
WHM maat fight bug

### ISSUE THREAD

**Issue by ultracato** [myera/issues#244]
fight dose not complete after holding hate for the required time limit
![img_20161106_120927](https://cloud.githubusercontent.com/assets/23299497/20041533/83612428-a41f-11e6-8d8b-15e67d627ad8.png)

**Comment by GM-Dave** [comment]
Sorry for the delay. Your character should be able to finish the quest and achieve their 75 cap.

If you have any further issues /tell a GM in game
