### ISSUE TITLE
Fishing guild shop inventory missing / glitched

### ISSUE THREAD

**Issue by KytioisaCat** [myera/issues#245]
The other day I bought things from the Fishing guild in Whitegate just fine. I then accidentally clicked Sell and then "Select from your inventory.". After this, selecting the Buy option will only show Cobalt Jellyfish and Mithran Fishing Rod and not the standard or custom inventory. This happened to both the Whitegate Fishing Guild and the Port Windurst Fishing guild shops. I tried zoning, relogging, waiting for server reset and asking another player to check the NPC (who told me it affected them also).

I was able to sell items that are normally in the guild inventory like Bastore Sardine upon which it showed up in the guild inventory again. However it only stocked one copy of the item sold and it was removed from the inventory list when bought back from the guild. Thus this is still a problem since I can't buy fishing equipment and bait that I and others need.

**Comment by GM-Dave** [comment]
This seems like an issue on the server side with the NPC's sales inventory becomming bugged (Windurst at least, Aht Urghan's seems to be fine)

Also for future reference when it comes to Custom NPCs/Vendors please use the Era HelpDesk ticket system.
