### ISSUE TITLE
Porter Moogle won't store any items any more

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#247]
I can still take out the items I had stored on the various storage slips (2, 4, 6, 7, 12) but when I trade the moogle an equip item and the slip to store something back, the moogle ignores the equip. It reacts as if I only traded him the storage slip and only gives me the option to take something out of storage.

I have asked other players about this and several people have mentioned that this happes to them as well.

Just thought I'd put it here, as I could not see a filed ticket for this yet.

Keep up the good work! :)

**Comment by GM-Dave** [comment]
This issue is being looked into, sorry for the inconvenience

**Comment by mathantolous** [comment]
I was able to store AF on slip 4 on 21/1/2017.  Have not tried any other slips as of yet.

**Comment by Minnaa** [comment]
I was able to store both AF and relic equip within the past week. (Slip 04 and 06)
