### ISSUE TITLE
My SMN does not have "Carbuncle" as a spell.

### ISSUE THREAD

**Issue by MyEraTeets** [myera/issues#250]
I'm unable to cast Carbuncle as a spell as SMN.  I have used him in the past, however the spell is no longer  listed along with all of my other avatars when I'm using SMN. I've attached 2 screenshots showing my available Avatars, as well as my current SMN level (51).

In game name: Teets

![img_20161119_165625](https://cloud.githubusercontent.com/assets/23587784/20459537/7efe9a9a-ae7a-11e6-90c2-a2748101bb58.png)
![img_20161119_165745](https://cloud.githubusercontent.com/assets/23587784/20459538/7f005088-ae7a-11e6-940a-7157e6dd86d7.png)

**Comment by GM-Dave** [comment]
This issue was resolved on the Era HeldDesk (Ticket number: 7412)
