### ISSUE TITLE
(Meditate bug) Samurai Relic hands

### ISSUE THREAD

**Issue by LyndonEra** [myera/issues#257]
when i meditate without them on i get 1000tp as expected but when i use the relic hands which is meant to give 200-400 extra TP i only get 800tp flat so its backwards at the moment.

**Comment by LyndonEra** [comment]
Aparently after some more testing it seems Its Meditate thats broken also

**Comment by GM-Dave** [comment]
Issue is being looked into

**Comment by GMYasiinEra** [comment]
fixed close please
