### ISSUE TITLE
Fishing Guild Stock

### ISSUE THREAD

**Issue by KalinaERA** [myera/issues#26]
The Fishing Guild fish stock was limited prior to the most recent update (ver 30160203_0) and now is almost non-existent. Chenon (Selbina) does not have a store at all and just talks about fish ranking. Graegham has only 4 types of fish and Mendoline only sells fishing rods. Babubu (Port Windy) sells basically nothing (1 rod and 1 fish). Ship to Mhaura also only has a few fish and rods (not sure if this was well stocked previously though). What's a chef to do :(

**Comment by Leelink1** [comment]
Chenon has his stock back. Think the rest are the same as pre update.

**Comment by KalinaERA** [comment]
Is there a way to have this list of fish restocked? This is from here: http://ffera.com/forums/viewtopic.php?f=3&t=22.

FISHING GUILD; Selbina

Gigant Octopus = 2,000g
Gavial fish = 1,500g
Titanictus = 2,000g
Gigant Squid = 1020g
Nosteau Herring 1,400g
Grimmonite = 10,000g
Nebimonite = 1,500g
Rhinochimera = 8,000g
Cone Calamary = 950g
Bastore sweeper = 200g
Bastore sweeper = 200g
Kalamar = 500g
Cobalt Jellyfish = 750g
Yellow Globe = 800g
Dil = 800g
Black sole = 800g
Three-eyed fish = 3,000g
Bhefhel Marlin = 1,358g
Gugru Tuna = 675g
Orge Eel = 320g
Kalkanbaligi = 2,000g
Pamtam kelp = 58g
Shining trout = 257g
Bastore sardine = 32g
Cheval Salmon = 134g
Gold Lobster = 2,016g
Zafmlug Bass = 261g
Bluetail = 2,520g
Red Terrapin = 3,546g
Tri-colored Carp = 195g
Dark Bass = 136g
Silver Shark = 3,400g
Bastore Bream = 6,048g
Giant Catfish = 770g
Icefish = 1,790g
Crayfish = 79g
Shall shell = 1,350g
Noble lady = 2,170g
Greedie = 24g
Quus = 60g
Copper frog = 132g
Emperor fish = 1,500g
Pipira = 500g
Bibiki Urchin = 1,500g
Moat Carp = 250g
Kilicbaligi = 2,000g
Lik = 3,000g
Brass Loach = 2,000g
Senroh Sardine = 150g
Contortopus = 2,000g
Bibikibo = 1,000g
Kayabaligi = 1,000g
Moorish idol = 2,000g
Coral Butterfly = 3,000g
Tiny Goldfish = 1,000g
Black Bubble = 2,000g
Crystal Bass = 5,000g

**Comment by Locodawg** [comment]
This has been resolved. Check NPC Graegham @ Selbina fishing guild.
