### ISSUE TITLE
Temenos-Eastern bug

### ISSUE THREAD

**Issue by Genesius1490** [myera/issues#265]
Killed the 4 Water Elementals on 5th floor of Temenos Eastern and path to next floor didn't appear.
we got stuck on this floor until time runs out.
screenshot of the 4elementals death here:
http://i.imgur.com/ztgvmwI.png
http://i.imgur.com/B9bIeZn.png
http://i.imgur.com/RC2IrzQ.png

**Comment by RoahZoe** [comment]
scarlet chip was replaced for now
