### ISSUE TITLE
Bastoc 8-1 Quicksand Caves

### ISSUE THREAD

**Issue by Tagman0073** [myera/issues#267]
Hello,
    I am on the second part of the Bastoc 8-1 mission where you have to go through the D-12 entrance of western altep to the quicksand caves. In the room where you drop down to goto the BCNM thre is supposed to be some ??? for a CS with Zied that are not in the room cant finsh that part of the quest.

**Comment by GM-Dave** [comment]
You didn't go down the correct path after re-entering the Caves post Antican fight.

http://ffxiclopedia.wikia.com/wiki/The_Chains_That_Bind_Us?oldid=781870

Go back to that point in the guide and follow the directions to exactly and you should be fine.
