### ISSUE TITLE
Buff Moogle  Disappear

### ISSUE THREAD

**Issue by furikazashi** [myera/issues#271]
Buff Moogle at Lowlands Yuhtunga  Jungle (G-11) isn't there anymore. There used to be one there that teleported us out as it gave us buffs but Yoshi stopped him from teleporting us. It has disappeared a few weeks after that.

**Comment by GM-Dave** [comment]
Yoshi has repaired the Moogle near the Outpost as well as a few other missing ones. It will probably take a proper server restart for them the server for the changes to made (as of this post the server has been up approx. ~34 hours
