### ISSUE TITLE
Sandy Mission "The Bat Hunt" Bugged

### ISSUE THREAD

**Issue by Killerelf** [myera/issues#272]
Hiya, im new to this server and started the rank mission the bat hunt but i get stucked after cs at the tombstone in KRT in a Black Screen. I cant move or something like that i just can write... i could have skiped the quest with crystals but now i cant cause i have the quest active can u reset the mission or can u complet the mission for me ?

**Comment by GM-Dave** [comment]
Please contact a GM ingame and well get this taken care of.

Also for future reference do NOT file 2 seperate tickets for the same issue, please file 1 ticket in either the HelpDesk OR Github (not both)
