### ISSUE TITLE
WHM Maat completed but no quest progress

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#273]
I completed the WHM Maat fight today for LB5, stayed alive until time was up. But now I can only start the quest with Maat all over. He is requesting another Testimony instead of finishing the quest.

Character is Minni. Sorry for the trouble, seems like many Maat fights bug out at the moment.

![img_20161217_230117](https://cloud.githubusercontent.com/assets/18585931/21290068/82ccc6d0-c4ad-11e6-8cc0-9a697de60123.png)

**Comment by GM-Dave** [comment]
It's unfortunate that LB5 Quests & Maat just tend to wonky when it comes to server updates.

Please contact a GM next time your are in game and reference this ticket.
