### ISSUE TITLE
Regional Vendors Not Working.

### ISSUE THREAD

**Issue by CheezeEra** [myera/issues#275]
So far I've tried Frost Turnips and Chestnuts. They all appear to have the dialog as if no nation controlled any of them.

**Comment by GM-Dave** [comment]
We'll look into fixing it. We are currently looking into removing most
regional/conquest restrictions from NPC Vendros because the system is so
borked.

**Comment by GM-Dave** [comment]
All region vendors have had their restrictions removed. You can shop from them at your leisure.
