### ISSUE TITLE
Unable to start quest "Bait and Switch" 

### ISSUE THREAD

**Issue by Enepttastic** [myera/issues#276]
http://ffxiclopedia.wikia.com/wiki/Bait_and_Switch

Went to talk to the quest starter, Salim and did not receive a cutscene. Went ahead and tried step 2(hitting the ??? at the altar) just to see if it was being weird but no progression. Yasiin was able to confirm that I had sufficient Bastok rep to trigger the quest and suggested I report to the tracker.

**Comment by GM-Dave** [comment]
The quest has not been coded/implemented by DSP nor is likely to be any time soon.
