### ISSUE TITLE
Despot PH's not up

### ISSUE THREAD

**Issue by Shdz** [myera/issues#277]
The room's that should have Groundskeeper are empty.

**Comment by GMYasiinEra** [comment]
[GM] Yoshi and I are looking into this. Thank you for bring it to our attention.

**Comment by GMYasiinEra** [comment]
Hey there has been a patch for this until we can get it back to retail design.. Kill the Groundskeeper's in the center.

**Comment by GM-Dave** [comment]
This has since been fixed and working as intended
