### ISSUE TITLE
Skull Of Gluttony Tallow Candle bug

### ISSUE THREAD

**Issue by Killerelf** [myera/issues#280]
Hiya, i just looked at the ah if there is an Gluttony Sword but there´s none and has been never sold to anyone. So i was just wandering if u can spawn him here on Era so i tryed it. U have to get all 7 Tallow Candels up but they just lit for 5 secends :/ and not for 5 min like on retail. Is there an other way to let him spawn?

**Comment by mathantolous** [comment]
I was involved in the initial testing when the trade to light was added and it was just spam the trade until all 7 pop. It does require 7 people and the timing of how long they stay lit is based on 2009 or earlier.

**Comment by Killerelf** [comment]
Okay thx for your Help :)
