### ISSUE TITLE
Sagheera not upgrading

### ISSUE THREAD

**Issue by cguisao** [myera/issues#281]
Hello,

I have been trying to upgrade the BLM AFv2 feet and have been unable to. I am trading the correct items 
Sorcerer's Sabots
Sorcerer's Sabots -1
Ether Holly
T. Whiteshell x28
and it still does not work. 

Thanks

**Comment by dwn134** [comment]
Try everything but the currency and see if it then asks to trade currency

**Comment by cguisao** [comment]
It did not work, I have tried most combinations but no luck yet. Sorry

**Comment by RoahZoe** [comment]
Sagheera still works,however it just has a different name (Palometa),because of you ffxi version(301612016_3) is too current and has alot of issues
