### ISSUE TITLE
KSNM30 Latent weapons

### ISSUE THREAD

**Issue by Genesius1490** [myera/issues#284]
Hey there, I got myself a Senjuinrikio not long ago and did the 500WS with it main-hand
but the dmg boost and crit rate never happened.
But i heard DSP did something to those weapons? so I was wondering what is it? and if not
,if anyone could look into them and fix them or anything /blush. 
Thank you very much

**Comment by GMYasiinEra** [comment]
I've since unlocked by default in the database
