### ISSUE TITLE
Overpowered Bomb-Tossing Goblins in Eastern Altep

### ISSUE THREAD

**Issue by VayleAkashi** [myera/issues#287]
The goblins in Eastern Altep are extremely overpowered with their bomb toss. Easy prey goblin one shotted me for 800+ hp and another easy prey goblin nearly one shot me for 500+ hp with bomb toss.

**Comment by dwn134** [comment]
What percent of hp did they have and what was your lvl and job?

**Comment by VayleAkashi** [comment]
I was level 52 or 53, the goblins had around 50% hp or less

**Comment by GM-Dave** [comment]
Did you have moogle or any other sort of buffs active at the time?

**Comment by VayleAkashi** [comment]
I had buffs from the field manual @ the outpost - Regen, Protect, and Reraise.

**Comment by GM-Dave** [comment]
Also what job & level were you?

**Comment by VayleAkashi** [comment]
I was in a party, we were level synced to 52 or 53. I was a thief, my other member was a warrior. We both took nearly the same amount of damage.
