### ISSUE TITLE
Dynamis mobs aren't spawning

### ISSUE THREAD

**Issue by Leif-Vivian** [myera/issues#29]
After this update Dynamis monsters are behaving strangely. Noticed this when we went into Dynamis - Beaucedine to farm some Attestations.  Only a handful of NPC's spawned at all and the Floating Eye's were nonexistent as well.  So att/win is not available right now without them.  Then when we went back in some of the zone spawned but we ended up calling it off because we were also experiencing lag issues.

**Comment by GM-Dave** [comment]
This was fixed with the 10/5 server update performed by sistern. Any new issues should be brought up with a new ticket.
