### ISSUE TITLE
Missing Archive Master

### ISSUE THREAD

**Issue by Tagman0073** [myera/issues#291]
I was trying to do the Fail Badge quest on Friskea after receiving the Faded Crystal i went to talk to the Archive Master who is not in the Arch Dukes bedroom or atleast i cant see him if he is.

**Comment by dwn134** [comment]
Check widescan. He might just be in another spot

**Comment by GM-Dave** [comment]
Recent update shouldve fixed most/all of the broken NPCs

Just double checked and this NPC is indeed ingame, though due to a bug his ingame model may be invisible (you can still however see him on widescan and target them when in range)
