### ISSUE TITLE
Crecsent Fang bug

### ISSUE THREAD

**Issue by jefferyrlc** [myera/issues#295]
When using Crescent Fang Blood Pact, even if Fenrir misses, it will still paralyze mobs.

<a href="http://smg.photobucket.com/user/1Enji/media/img_20170131_210341.png.html" target="_blank"><img src="http://img.photobucket.com/albums/v70/1Enji/img_20170131_210341.png" border="0" alt=" photo img_20170131_210341.png"/></a>

**Comment by GMYasiinEra** [comment]
fixed
