### ISSUE TITLE
Chocobo Jig + Tonko

### ISSUE THREAD

**Issue by Oyalit** [myera/issues#3]
The Chocobo Jig "Quickening" effect wears off whenever Tonko: ichi is cast on myself.

Edit, noticed this also happens when I cast Utsu on myself.
Edit, and Also Momoni, I'm guessing it wears off if any buff is cast on me. It's only supposed to wear if attacked.
![ticket](https://cloud.githubusercontent.com/assets/17228889/13031829/12b614a2-d2a8-11e5-9d38-e287b3185a0e.png)

**Comment by Locodawg** [comment]
Confirmed as of today, this is till an issue.
