### ISSUE TITLE
MISSING ITEMS - Swan bilbo, Volunteer's Nails

### ISSUE THREAD

**Issue by Umbasa** [myera/issues#300]
Hello.   I've come across two mobs that usually drop very decent gear for Bard/Beastmaster.  One is Cwn Cyrff, who is supposed to drop the sword "Swan bilbo".  The other is Merrow No.5 who is supposed to drop the boots "Volunteer's Nails".   

I've killed these monsters multiple times and clarified with GM's that both items are not in the game. I know for sure that they existed in the timespan Era is trying to emulate.  If at all possible those items could be added, I would be very grateful.   Thank you for your time and keep up the great work!

-Umbasa

**Comment by GM-Dave** [comment]
Considering you filed a ticket for this on the HelpDesk, filing one here is redundant so I'll just be closing it. Please watch the HelpDesk for tracking purposes.

For future reference missing drops/NMs in areas past CoP is likely just unimplemented content, and as such probably hasn't been worked on at all in DSP. Content requests should either be done via the forums or maybe check to see if its something else being worked on via DSP's github.

Actual missing content (such as drops) are better off being ticketed via the HelpDesk ("Service Requests" in the "report" menu on the main site) as it is probably a database issue with Era, and not necessarily all of DSP.
