### ISSUE TITLE
Rose Garden / Voluptuous Vilma no show

### ISSUE THREAD

**Issue by RoCo87** [myera/issues#301]
Decided to camp Rose Garden / Voluptuous Vilma for my second character, but am having problems spawning them.
I got the ring for my first after a server reset, but I believe that the spawn conditions have been altered since. However, I have camped it - after server live for 1day+ - and no sighting of either Rose Garden, Vilma or the PH over the course of 90mins.

**Comment by GM-Dave** [comment]
> no sighting of either Rose Garden, Vilma or the PH over the course of 90mins.

I'm not sure you know/understand how Rose Garden/Volutuous Vilma works, lol. I would suggest doing some research on it via the FFXIclopedia if you haven't already, and know I've personally confirmed it to work as closely to retail as can be. My only suggestion would be kill the PH once proper immediately after a server reset to make sure the timer is set properly.
