### ISSUE TITLE
Lava/Kusha rings both giving latent effect separately when both equipped

### ISSUE THREAD

**Issue by KytioisaCat** [myera/issues#302]
http://ffxiclopedia.wikia.com/wiki/Lava%27s_Ring

http://ffxiclopedia.wikia.com/wiki/Kusha%27s_Ring

Lava's and Kush's rings should give the latent one time if both are equipped at once. From a test a GTC member did with /checkparam, when both are equipped they are giving off the latent once each individually. This results in the set latent effect being double the intended effect.

**Comment by LocoFFEra** [comment]
This has been fixed.
