### ISSUE TITLE
SMN pet attacks claimed mobs of party I'm healing

### ISSUE THREAD

**Issue by Skye12977** [myera/issues#305]
I'm using a SMN, named SKYE, to heal my mentor, Ragnar, and after I healed Ragnar Carbuncle decided to take to combat and steal the monster. The monster was a Ghoul from Valkrum.

**Comment by dwn134** [comment]
Did ragnar have claim of the mob already and then carby stole it? And were you both in the same party?

**Comment by GMYasiinEra** [comment]
* leaves ticket .. never checks back *
