### ISSUE TITLE
Off-hand Weapon Stays Equipped After Switching SJ

### ISSUE THREAD

**Issue by Lambent32** [myera/issues#308]
After switching from BLU/NIN to BLU/WHM my off-hand sword appeared to be still equipped. unequipping main weapon or swapping it for another doesn't seem to change anything.  Off-hand sword still performs draw animation but doesn't attack.

**Comment by dwn134** [comment]
Its a known dsp bug. Its just a visual bug and changes no performance of your character

**Comment by LocoFFEra** [comment]
This is a visual bug, the way to fix it is to create a lockstyle with the offhand sword in the same slot it's stuck in, lockstyle it, then remove your lockstyle, and create a new lockstyle and lockstyle it. 

After that's done, it will remove the stuck visual. This is technically a lockstyle related bug.
