### ISSUE TITLE
Trash enemy doing huge damage from excessive range, Halvung

### ISSUE THREAD

**Issue by whateversclever1215** [myera/issues#309]
This affected some of my LSmates

The zone was Halvung, time was 9:25PM CST or so.
They had a trash mob, Friar Lantern, "Cast Firaga3 from 70 yalms and it did 100%+ damage", it wiped them during an easy NM fight.
They were farming for Bomb Cores and had already successfully gotten 3-4 already.

**Comment by GM-Dave** [comment]
Any further information or documentation you could provide for this?

**Comment by whateversclever1215** [comment]
This did not directly happen to me so this is about all the information I have.
I believe the LSmate that had this happen was Kruxx, but this was 10 days ago and I don't really remember. Closing this ticket is fine if you cannot reproduce.
I would assume all that is necessary is to go to where bomb core NM is spawned, and test how much damage trash mobs are doing with their spells, possibly test mob aggro range or mob spell casting range.

**Comment by GMYasiinEra** [comment]
-ga need to be soaked.. and mobs stop casting @ 36 yalms.. my guess is kruxx tried to run away to interupt and ate the hit alone.. lvl 80+blms tend to hurt you with ga spells lol
