### ISSUE TITLE
Unable to access Riverne - Site #B01

### ISSUE THREAD

**Issue by NyanNyanSquad** [myera/issues#310]
When activating the Spatial Displacement outside of the zone, the message simply asks "Proceed onward?". I do not get a choice of which zone I wish to enter. 

Client is fully updated.

**Comment by dwn134** [comment]
But do you have the mission status and all cs's to be able to enter this area? If you dont you can only enter a01

**Comment by NyanNyanSquad** [comment]
Yes. I am currently set up for Diabolos fight. I got this access years ago. Back when the portals didnt function properly. It's since been recoded/cleaned up. Could have something to do with this. This is happening for both of my characters, Azunyan and Amallia. 

Since this ticket is a month old, I am going to run down and see if this is still happening. Will post a follow up.

**Comment by dwn134** [comment]
Diablos is cop 3.5 fight and B01 area is not accessable until 4.1 so if you were able to get there before it was a glitch. It is work as per retail now. If you can, please close your ticket and reopen it if you have problems after cop 4.1.

**Comment by NyanNyanSquad** [comment]
Ok. Thanks for the reminder and your time. <3

**Comment by dwn134** [comment]
Dont forget to close the issue. Thanks for playing
