### ISSUE TITLE
Gourmet quest set to retail levels

### ISSUE THREAD

**Issue by VayleAkashi** [myera/issues#311]
Greetings,

The Gourmet quest with Salimah in Bastok is reset to retail levels. She pays 490 gil per and you have to zone between trades. 

Thanks! 
Vayle 

![ffxi_2017 04 05_17 55 08](https://cloud.githubusercontent.com/assets/25160527/24731785/8439a7d2-1a29-11e7-99b0-278d9f9771a4.png)

**Comment by GMYasiinEra** [comment]
looking at this screenshot leads me to believe you traded her a sleepshroom outside the requested time frame.. equaling 100gil(retail) seeing how she said "i guess this will do" which would make sense considering your recieved 490gil.. also the quest does state that you need to zone between trade.. did you refer to the wiki?

**Comment by VayleAkashi** [comment]
Absolutely, I read the wiki. 

In the context of Era, this is a custom quest to give new players more gil. Refer to the custom quest information located at [http://ffera.com/wiki/index.php/Making_Gil](http://ffera.com/wiki/index.php/Making_Gil)

Thanks! 
Vayle

**Comment by GMYasiinEra** [comment]
trading her the item at any other time will give 100 gil.
Sleepshroom: Trade during 18:00-5:59 for 200 gil
Treant Bulb: Trade during 6:00-11:59 for 200 gil
Wild Onion: Trade during 12:00-17:59 for 350 gil
( Straight from wiki )

therefore... you actually got more then what you should... (490 gil) i checked the cs id for what she replied too.. you should've only received 100 gil..

**Comment by VayleAkashi** [comment]
Yasiin, In the context of retail, your statement is correct. However, if you refer to the era link provided [http://ffera.com/wiki/index.php/Making_Gil](http://ffera.com/wiki/index.php/Making_Gil) this quest was customized to give new players more gil per turn in (much like the ladybug wing quest), no matter the time it is turned in, without requiring them to zone. 

_"Gourmet - this quest takes either Sleepshrooms, Treant Bulbs, or Wild Onions, which can be found easily if you're a low level player. Also Era has customized it so you don't have to change areas to turn another item in.
La Theine Plateau has a Fields of Valor page specifically for Funguars, and you'll gain Sleepshrooms while killing them. You can solo level from 14 to 22 there, so it's a great time to do this quest."_

You can also view AraY's guide to making money on the forums [http://ffera.com/forums/viewtopic.php?f=18&t=24](http://ffera.com/forums/viewtopic.php?f=18&t=24) which references what the quest was like up until the DSP update a month or so ago. 

_"2. Repeatable Quests - The Gil rate on this server is retail x5, so this means that there are a TON of repeatable quests that can be done to earn a decent amount of Gil.

The first repeatable quest that comes to mind that is probably the easiest for new players to do is one in Bastok Markets called Gourmet

To start this quest you talk to Salimah in Bastok Markets (L-8) then you will have to trade Salimah one of three items; 1 Sleepshroom, 1 Wild Onion or 1 Treant Bulb. Doing this quest will give 1000 Gil each time it is completed and it can be completed at whatever time and as many times you want and it still gives 1000 Gil per trade (don't worry about what it says on Wiki about trading items at different times, it's been modified on Era). These items are easily obtainable at low levels, the Treant Bulbs can be obtained in various areas whilst levelling, they can be obtained from saplings in the following areas; North Gustaberg, South Gustaberg, La Theine Plateau, Konschtat Highlands and Tahrongi Canyon. The sleepshrooms can also be obtained whilst leveling, they can be obtained whilst doing page 3 in La Theine Plateau (kill 8 Poison Funguar) this page can be easily solo'd at level 15-16 and will get you to 21 (this is how I advise new players to get them). That is not the only way to get them, new players can also kill Forest Funguar in East and West Ronfaure. Lastly the Wild Onions drop from low level goblin thugs in low level areas, the drop in; East/West Sarutabaruta, East/West Ronfaure, North/South Gustaberg, La Theine Plateau, Konschtat Highlands and Tahrongi Canyon. However the best way to obtain them is by going into King Ranperre's Tomb and killing the Goblin Thugs in there."__

I did not post this to get compensated for the quest not working. I posted this ticket to get the quest working as it was customized on Era until the DSP update. It is an important quest for very new players on the server to make gil for low level gear purchases. I know I made loads of gil off it when I first started.

**Comment by GMYasiinEra** [comment]
all im saying is i looked at it.. it works as per retail..

**Comment by LocoFFEra** [comment]
This has been resolved.
