### ISSUE TITLE
Nexus Cape broken?

### ISSUE THREAD

**Issue by ValentiFFXI** [myera/issues#313]
The last two or three times I've tried to use the nexus cape, it doesn't work. I checked wiki to be sure my party leader's zone is eligible, but after equipping the item and waiting for the countdown, it remains grayed out in my inventory and unable to be clicked/activated.

**Comment by ValentiFFXI** [comment]
I think I figured this out. The item was in my mog wardrobe, not my inventory. Moving it seems to have fixed it.

**Comment by GM-Dave** [comment]
Keep in mind this is the same for ALL usable equip items, they all must be in your actual inventory to use. I.E. Warp Cudgels, Ecphoria Rings, etc
