### ISSUE TITLE
lol Eldieme coffer keys from bostanieux omelette

### ISSUE THREAD

**Issue by whateversclever1215** [myera/issues#316]
I was hunting coffer keys for black mage AF armor
your website said that Eldieme coffer keys had the highest droprate off Nachtmahr mobs in Bostaunieux Oubliette. like twice as high droprate as any mob actually in eldieme. I farmed 4 keys there to confirm it's really working that way. I think this is a bit silly and probably not intended.

**Comment by GM-Dave** [comment]
Thank you for bringing this to our attention. I will forward this to the devs/admins to look at and fix.

For future reference item/mob drop issues are generally a Era database issue, and as such the better choice is to file a ticket via the HelpDesk (Service Requests under Reporting on the main page)
