### ISSUE TITLE
Dangruf Waldi geyser at I-8 not working

### ISSUE THREAD

**Issue by lancet1** [myera/issues#319]
Trying to do the Drachenfall quest, but geyser not erupting.  I am not on Chocobo.  Not sure if the other geysers are working for the remainder of the quest, as I can't get past the first one.  Thanks!

**Comment by dwn134** [comment]
It works but u have to stand on it just right and wait. I dont think theres
an animation you just get moved

**Comment by lancet1** [comment]
Great, it worked.  Thanks!  You are right, there is no animation.

**Comment by dwn134** [comment]
If you could please close your ticket
