### ISSUE TITLE
quu domi and mee deggi

### ISSUE THREAD

**Issue by Brooster** [myera/issues#32]
been camping mee deggi and quu domi for hours and hours and have yet to see them spawn. yes im killing the right ph's. im not sure if i have that bad of luck or if the update has messed them up. also on the quu domi side the yagudo heralds if you stand within range will just randomly hit you with a ranged attack without aggroing. it doesnt matter the level because i was there at 75.

**Comment by KalinaERA** [comment]
Both of those NMs are listed as Scripted in the monster database. So this issue is directly related to this one: https://github.com/myera/issues/issues/30.

**Comment by Leelink1** [comment]
These should be working now.
