### ISSUE TITLE
Single-target spell wipes shadows

### ISSUE THREAD

**Issue by ValentiFFXI** [myera/issues#321]
I was fighting a demon in Castle Zvahl Baileys. It started casting Stone IV, but I didn't worry because I had three shadows up. Except the spell dropped my three shadows and dealt enough damage to kill me.
![bug](https://cloud.githubusercontent.com/assets/27043553/25114605/0119d9ec-23bd-11e7-9d25-8d14dc1d2cb8.png)

**Comment by GMYasiinEra** [comment]
this screen shot proves that you had 0 shadows up when the spell went off
