### ISSUE TITLE
Pup merits, skills catagory

### ISSUE THREAD

**Issue by dwn134** [myera/issues#322]
I capped the skills catagory before i was acually had the native skills capped and now i cant skill up to where they should be.
stuck at 230/235 melee and 277/286 magic and my ranged worded so far since its 10/10
![img_20170418_170137](https://cloud.githubusercontent.com/assets/17234748/25155310/064d1ada-245a-11e7-8eeb-5ef9a3cef7d2.png)

**Comment by GMYasiinEra** [comment]
this has been resolved close plox
