### ISSUE TITLE
Unobtainable items for Grumblix

### ISSUE THREAD

**Issue by NyanNyanSquad** [myera/issues#324]
Cursed Clogs

Red Storm Lantern (if this is obtainable, I was unable to find "Nopales" to make "Red Textile Dye")

Leather Pot

Keep up the good work guys. I now pee in Gatorade bottles because of this quest.

**Comment by Miscbox** [comment]
Leshonki bulb not on drop table for relative NM for "Rosenbogen."

**Comment by NyanNyanSquad** [comment]
Cursed Breastplate Just came up as well

**Comment by NyanNyanSquad** [comment]
Water Spider's Web isn't in the item DB

**Comment by NyanNyanSquad** [comment]
Birdman Cape

**Comment by NyanNyanSquad** [comment]
Cursed Cuishes
