### ISSUE TITLE
Can't start PUP AF quest

### ISSUE THREAD

**Issue by ryin77** [myera/issues#328]
I'm talking to Iruki-Waraki as a lv 55 PUP and he won't start the quest.

**Comment by GMYasiinEra** [comment]
hi thats because it isnt coded.. if you use the website to search for the items you are in seartch of you will see that they drop off the sicklemoon jagils in mount Zhaylom

**Comment by ryin77** [comment]
Oh. Thanks.
I tried looking in the era wiki and searched the forum for the puppetmaster/general artifact quests. I know the wiki is mostly outdated, but can someone add PUP to the list here?
http://ffera.com/wiki/index.php/Artifact_Armor_%26_RSE

**Comment by GMYasiinEra** [comment]
http://ffera.com/items.php?id=14523

**Comment by GMYasiinEra** [comment]
you use  the tools on the main page

**Comment by GMYasiinEra** [comment]
items monsters character etc.
