### ISSUE TITLE
Bst causing crash to desktop

### ISSUE THREAD

**Issue by Dinga84** [myera/issues#331]
I can't seem to replicate it reliably, but Beastmaster seems to cause lots of crash to desktop since the Windower issue a week or two ago.  I noticed it's generally on large gear swaps, such as when using Reward or Charming something.  I apologise if I cannot give more information than this or take any screenshots, as the game simply closes.  My best guess is that it's a Windower issue, if that's the case it's out of our hands until they fix/update it for the recent changes they did.

**Comment by LocoFFEra** [comment]
Has this issue happened since the original time? I haven't had any other tickets about it, please let me know.

**Comment by GM-Dave** [comment]
Since OP hasn't replied and there have been no other documented instances of this issue, going to assume it is resolved and close the ticket.
