### ISSUE TITLE
Ninja!!!!! i Would like to see nin work like this please

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#334]
IN/DRK is much like playing PLD. If you've played PLD before then you'll understand the idea of holding hate without damage. Familiarize yourself with Enmity values to each Job Ability and Spell. The difference between PLD and NIN/DRK becomes very clear on long fights as NIN/DRK gets more options to spells with non-decaying enmity, particularly Aspir and Absorb-TP. Both of these spells take a considerably long time to cast, especially in comparison to Stun but all three of these spells have an element of non-decay enmity that should be cast repeatedly throughout the fight. I'll provide some specific examples of how I used NIN/DRK back at Level 75. Most of these strategies are obsolete now, but knowing how to do it becomes invaluable in knowing specific ways to play the job.

Kirin/Proto-Omega
Kirin and Proto-Omega use to be kited fights, usually done by PLDs because they were the symbol of hate holding and survivability. Kirin casts Stone V, Quake, and Stonega IV and runs REALLY fast. His basic attacks are virtually all TP moves that cause Bind, Choke, and Rasp. What you had to do to stay alive was keep shadows up and run like hell. Stonega IV formerly was a devastating spell and there was no way to block it other than running away, and Kirin had a very high resistance to Stun being an earth based NM. But kiting involves a lot more than just running away from something and just keeping your shadows up. You need to maintain a high level of hate so that your DDs and Casters can do their jobs and not be the target of its attacks. Single target spells such as Stone V and Quake provided opportunities to cast multiple spells in succession while not having to worry about taking a high damage spell to the face. Quake in particular let me cast Aspir, Sleep (The spell Sleep used to have the VE and CE values of Absorb-TP), Hojo/Kurayami: Ni and still have time to throw out the nearly instant cast Stun and have some distance from Kirin. Stun itself is probably the most important spell to use because it is the DRK equivalent to Flash. Having a Haste setup ensures that Stun is ready to use faster than Provoke. Kited NMs that are easily stunned like Proto-Omega allow for breathing room to cast Utsusemi: Ni when you stun them. As long as you aren't hit by massive hate reset moves like Colossal Blow or killed while Kiting holding hate without dealing damage becomes a easy routine.
Proto-Ultima
Proto-Ultima is a good example of a NM that does not move and NIN/DRK becomes a more than suitable replacement for a PLD. When I tanked Proto-Ultima I chose not to use my Katanas as I had my Limbus group damage him in a controlled manner. Oftentimes when I did use my katanas he would ready TP moves much more frequently and have more than 2 shadows wiped from me as well as the DDs I had come in to weaponskill. Yes, you can and I have used my katanas on Proto-Ultima, but for the purposes of this example I used a staff so damage is not a factor in holding hate. The idea is the same but Stun becomes an important spell because many Sea NMs are easily stunned, even from a DRK sub. Proto-Ultima has an ability that puts both Slow and Elegy on you, which need to be erased by your support immediately. While fully buffed with Marches, Haste, and refresh, you should be able to be as busy as if you were using your katanas. That means keeping a full routine of Stun, Aspir, Sleep(Absorb-TP), Kurayami/Hojo/Jubaku. If you're ever at the point where you have nothing but cooldowns, you can spam Poison for 5mp and 1 sec recast. As long as you're constantly taking action most of your DDs and Casters can do their job worry free. And should the situation arise that someone rips hate off you or you're hit with a hate reset move you can always use Souleater or Last Resort to spike up hat

**Comment by GM-Dave** [comment]
This is not the place to post requests, this should only be used for bugs in game.

If you really want to make this or other requests please post them in the forums.
