### ISSUE TITLE
Shield Bash

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#335]
Shield Bash doesn't have Stun effect.

**Comment by dwn134** [comment]
I read over the lua and its scripted to have a random stun and i will test it tonight.

**Comment by dwn134** [comment]
tested it today and i got a stun status everytime with aegis.  shield size does play a part in damage and blockrate

**Comment by Aerixaa** [comment]
I aggree it does work on normal Mobs but dosnt work at HNM at all >.< I could Stun god and i didnt Aegis or relic hands or knighly earring on retail >:>

**Comment by dwn134** [comment]
tested on HNM today it does work with a low success rate about 1 in 6

**Comment by GMYasiinEra** [comment]
Read the wiki please... the dmg and enmity work fine as for the stun it takes into account lvl differeneces between you and the mob
stun wont always work if the mob is 20-25 lvls higer then you..
