### ISSUE TITLE
Holy water crafting

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#342]
Hi i try to craft Holy water 

Light Crystal
KeyItemTrituration
3 x Distilled Water
1 x Triturator

Dosnt work always get message 

"Synthesis cannceled. That Combination of materials cannot be sythesized

And yes i have KEy item

**Comment by dwn134** [comment]
Ill try it tonight and look into it. It might have the wrong KI attached to it

**Comment by dwn134** [comment]
correct it is broken, i have submitted the fix

**Comment by dwn134** [comment]
Has been fixed now. Can close ticket
