### ISSUE TITLE
Buffalo hide

### ISSUE THREAD

**Issue by ericnuke** [myera/issues#37]
Buffalo hide cannot be crafted into buffalo leather, the synth does not exist

**Comment by MarkWaldron** [comment]
I see 3 recipes for it in DSP. Can you specify which recipe you tried that didn't work? 
INSERT INTO `synth_recipes` VALUES (1041,1,2018,0,0,0,0,0,49,0,0,4103,4245,635,635,635,1628,1628,1628,2129,4509,1629,1629,1629,1629,3,3,3,3); // builk synth 
INSERT INTO `synth_recipes` VALUES (1042,1,0,0,0,0,0,0,49,0,0,4103,4245,635,1628,4509,0,0,0,0,0,1629,1629,1629,1629,1,1,1,1);  //Win tea leaves
INSERT INTO `synth_recipes` VALUES (1043,1,0,0,0,0,0,0,49,0,0,4103,4245,695,1628,4509,0,0,0,0,0,1629,1629,1629,1629,1,1,1,1); // Willow Log

**Comment by Locodawg** [comment]
This has been resolved.
