### ISSUE TITLE
Trick Attack is not stacking with Weaponskills properly

### ISSUE THREAD

**Issue by Manticmage** [myera/issues#38]
When using Trick Attack with a weaponskill in front of the mob with a person lined up properly between you and the mob, Trick Attack Weaponskill does not activate. No enmity is transferred to the person in between, and the damage is not boosted. The testing characters were 75, so the THF had the Assassin job trait that allows for this.

**Comment by GM-Dave** [comment]
This is an old ticket and the issues had been resolved some time ago. If this is still an issue please file a new ticket.
