### ISSUE TITLE
Darkness named. Cop 3-5 on hard mode

### ISSUE THREAD

**Issue by dwn134** [myera/issues#39]
Just tried to do the fight. Blm with capped dkills and merits did 5 damage at most with a fire 2. Most nukes just did 0 damage. Melee attacks where the same. Almost no damage at all. After 7 mins of fighting him with blm whm pla sam and mnk he was still at 100. Went to 99 but a few times but regened to 100 soon after

**Comment by Sanlord** [comment]
Sometimes Diabolos's level will not be okay, just try again :) 2 Healers and 4 Melees worked for me.
