### ISSUE TITLE
No Pizza/Pasta

### ISSUE THREAD

**Issue by coalbed** [myera/issues#4]
Hey with fishing gone, there is no more sandfish or icefish, That means no more Anchovy, which means no more Marinara sauce. No sauce, no pizza or pasta, some of the best food in the game. I asked a few cooks after I couldn't find these and the ones that were here when fishing stopped last time, knew to stock up. That said, I didn't know. These small stocks will run out. Maybe a place has been added for them but the wiki not updated? maybe it is intended not to have pizza and pasta. I don't know. Just bringing it to the attention of the bosses. thanks, Boni/Waya/Waysa

**Comment by Scavenge** [comment]
i'll see if i can temporarily turn on fishing guild limited stocks until i can be sure fishing won't lag the server to death.  or maybe lee will see this first and do it.

**Comment by coalbed** [comment]
Hey thanks allot, and thanks for the all the hard work to keep all of this going.

**Comment by Leelink1** [comment]
Added the fish to the fishing npc for the time being.
