### ISSUE TITLE
Summoner quest

### ISSUE THREAD

**Issue by Taladric** [myera/issues#40]
Received all colors 3 times but still not getting cut scene where carbuncle goes to la theine, go to circle ??? And nothing when trading. Not sure what I'm doing wrong.

**Comment by Leelink1** [comment]
Which character is this on. It says Taladric hasn't started the quest.

**Comment by Taladric** [comment]
Sidewalkchalk, sorry wrote for a friend and forgot to mention character name.

**Comment by Taladric** [comment]
![img_20160322_112848](https://cloud.githubusercontent.com/assets/18010035/14005854/a2556b18-f124-11e5-8e98-902e65cf8d5d.png)
![img_20160322_114440](https://cloud.githubusercontent.com/assets/18010035/14005857/a259bc4a-f124-11e5-80e0-674f803b369c.png)
![img_20160322_114959](https://cloud.githubusercontent.com/assets/18010035/14005855/a2564876-f124-11e5-85e1-fba316599b26.png)
![img_20160322_210824](https://cloud.githubusercontent.com/assets/18010035/14005856/a257103a-f124-11e5-80f2-c3dcb6e3bf02.png)
![img_20160323_132859](https://cloud.githubusercontent.com/assets/18010035/14005860/a271d3b6-f124-11e5-8470-83f684f2f0df.png)
![img_20160323_134058](https://cloud.githubusercontent.com/assets/18010035/14005858/a25aed5e-f124-11e5-956b-69459f05d5da.png)
![img_20160323_150728](https://cloud.githubusercontent.com/assets/18010035/14005859/a267fc06-f124-11e5-8cfa-cec639bdaee5.png)

**Comment by RunAwayDSP** [comment]
Late to the party.. I assume this is good now but no earth when you posted screenshots :)

**Comment by renowaik** [comment]
I seem to be having this same issue. I started the quest a month ago, and have received all the cutscenes, but trading the gem to the ??? does nothing.

Spoons

**Comment by GM-Dave** [comment]
This issue should be resolved. Keep in mind due to other ongoing issues it may take several "zoning" attempts to get the event to count towards progression.
