### ISSUE TITLE
Ruebezahl NM isn't working as intended

### ISSUE THREAD

**Issue by Leif-Vivian** [myera/issues#41]
Just tried to kill this NM for the lvl 70 rse belts and he was doing a few odd things. First he was able to be one-shotted and then he spawned right after being killed instead of the 2-hour reset he is supposed to have. Second he didn't drop anything but 1-3 gil, tried killing him a few times to test this out.  Third he spawned invisible a few times as you can see in the screenshot.  
![img_20160323_192836](https://cloud.githubusercontent.com/assets/17759410/14005245/7396602e-f12f-11e5-876c-6479ff52d8ae.png)

**Comment by Leelink1** [comment]
Will work next restart

**Comment by Leif-Vivian** [comment]
Thanks Lee! Going to go ahead and close this one!
