### ISSUE TITLE
Desert boots movement speed isn't working

### ISSUE THREAD

**Issue by Leif-Vivian** [myera/issues#42]
Hi there! Just crafted a pair of desert boots and I am unable to get the 12 percent movement speed bonus while under the effect of sandstorm.  
![ss 2016-03-24 at 11 39 05](https://cloud.githubusercontent.com/assets/17759410/14024137/db3da904-f1b5-11e5-8d68-881d6a902a9f.jpg)
![ss 2016-03-24 at 11 47 37](https://cloud.githubusercontent.com/assets/17759410/14024235/47726d58-f1b6-11e5-9cbf-acb31e3b1bac.jpg)

**Comment by dwn134** [comment]
Has been fixed. If you can please close your ticket
