### ISSUE TITLE
Weaponskills all missing

### ISSUE THREAD

**Issue by FleabittenGrey** [myera/issues#44]
I have never made a ticket on this so forgive me if I am doing this wrong.  I did not see a ticket so I figured I would file one - after the crash around 6PM, all weaponskills consume TP but miss every single time.

**Comment by Leelink1** [comment]
Should be good now

**Comment by FleabittenGrey** [comment]
Hey Lee.  Server crashed about 20 minutes ago and the weaponskills broke again.
