### ISSUE TITLE
Bastok Mission 9-2 - Where two paths converge

### ISSUE THREAD

**Issue by cryogenic1** [myera/issues#46]
Just wanted to report an issue with this BC.

Did the fight, killed Zeid, but then got locked out of my controls as if I'd won the BC and was about to be shown a cutscene. For the record, killing Zeid is the only thing you're supposed to do to win. This happened immediately after I killed him.

....except, nothing happened. I ended up just watching my character die as the two "shadow" adds I had slept woke up and killed me while I couldn't do anything, since the game seemed to be trying (and failing) to prepare a cutscene.

Went to talk to the npc (iron eater) to see if it had registered my win, but it did not as I just received the normal generic non-mission dialog.

Won the BC, lost some exp, didn't get credit. :)

Anyway, thanks for reading!

-Cryogenic

**Comment by GM-Dave** [comment]
This issue should be resolved. If you by chance still have issues, please file a ticket via the Era HelpDesk (Service Requests) on the main page and contact a GM in game.
