### ISSUE TITLE
Drain Quest Bugged (The Rumor)

### ISSUE THREAD

**Issue by Chlymera** [myera/issues#47]
While trying to trade Novalmauge his beastman blood in Bostaunieux Oubliette nothing happens and he does not give me the Scroll of Drain. 

I have met all requirements for this quest:

Sandy Fame 6 - http://puu.sh/nY35z/9bfeb928bb.png
Past Mission 2-3 (currently Bastok Mission 4-1)

I believe the issue might be server side somehow? When I check my character profile on the forums my Sandy fame is not updated and still showing Rank 1. But in game, it is obviously Rank 6. 

Any help would be appreciated. I <3 drain.

**Comment by dwn134** [comment]
Tank doesnt matter. Its fame. Also you cant go by the town fame checker. They dont work. Can you start the quest and its in your quest log?

**Comment by Leelink1** [comment]
You fame is level 2.

fame sandoria	440 (2)

**Comment by Chlymera** [comment]
I wasn't aware Fame NPCs didn't work on the server. How can I check my fame for each city without the NPCs?

**Comment by dwn134** [comment]
on the era sight, Link charater data button, the profile, fame points

**Comment by Locodawg** [comment]
This has been resolved.
