### ISSUE TITLE
Worm's Turn Group 2 drops broken

### ISSUE THREAD

**Issue by Hokuten85** [myera/issues#50]
Group 2 item drop rates need to be adjusted.  It has 7 scrolls all with a 25% chance at dropping.  DSP code will check the items one at a time to determine if an item drops and then breaks out of the loop once it has found an item.  In order to get Utsusemi: Ni from this BCNM, because it's the 7th item listed in the database, the drop determination process would have to fail 6 checks in a row at 25%, and then pass the 7th.  This is like some 4% chance that this could ever happen.

It would be super awesome if my group could get seals refunded, since it appears this is not working correctly.

**Comment by Hokuten** [comment]
I believe I read DSP wrong. I think if drop percentages in the group add up to over 100%, I think it effectively proportionally scales them down to 100%. In this case each item in the group would be about a 14% drop rate.

So,  less of an issue than I originally thought... but the Era item tool on the website is a little misleading.

**Comment by GM-Dave** [comment]
Worm's Turn is a disallowed/nonworking BCNM anyway, and isn't accessible.
