### ISSUE TITLE
cop 5-3 tenzen path

### ISSUE THREAD

**Issue by dwn134** [myera/issues#51]
http://ffxiclopedia.wikia.com/wiki/The_Pursuit_of_Paradise_(Tenzen's_Path)

1st part  there are 2 avatar gates for cs's required in Pso'Xja. the 1st cs is supose to come from tower 5 but can only get the cs from tower 6 avatar gate.

2nd issue is i cant trigger the cs for the 2nd avatar gate from either. i even went back and tried all my cs's over again which i have got them all upto the point of needing the scene for this on.
I'm doing this mission on 4 people and they all are getting the same problem

**Comment by Leelink1** [comment]
If you send me a tell when you are at the avatar gate we can look why. Your at the point of needing to go to the second avatar gate.

**Comment by dwn134** [comment]
the 2nd cs is from the same avatar gate at tower 6. problem getting it to work is theres a cs when entering the tower. you have to leave and zone back in until you stop recieving the cs took all my people 3 times zoning before it took. so I'm all good now
