### ISSUE TITLE
Mission 5-1 - Darkness Rising

### ISSUE THREAD

**Issue by Myronnis** [myera/issues#53]
Me and a friend are both on the same mission, (Mission 5-1) we got the CS talking to Naji which gave us the New Fei'Yin Seal and they told us to go to Fei'yin, entering Fei'yin we should have received a CS but we didn't.

we backtracked, talked to Naji again didn't get any CS, went to San D'oria to make sure, Ranguemont pass and didn't get anything either, rezoned Fei'yin twice didn't get any either.

stuck on that step

**Comment by Leelink1** [comment]
Hey, You need to zone in to Fei yin from Beauc. Thats the only way to get the cs.

**Comment by Myronnis** [comment]
We did, at least Sab did and he didn't get it

**Comment by Myronnis** [comment]
Well I tried again this morning, got stuck in a Blackscreen kinda cutscene, with a sad melody, but I have to unstuck to get out of it.

**Comment by Myronnis** [comment]
just to make sure, I don't get the "cutscene" so I can't get the BCNM to work either

**Comment by Leelink1** [comment]
Give me a tell in game and were look into it

**Comment by Locodawg** [comment]
This has been resolved.
