### ISSUE TITLE
cop 6-4 One to be Feared

### ISSUE THREAD

**Issue by dwn134** [myera/issues#56]
cant complete this mission, after every stage when you click door for cs and next fight 1 or more people will get a POL error out of game. We have tried it 10 times lastnight have made it to ultima with 2 people 1 time but was unable to kill him with just that. Had GM help after 5th try and even they couldnt get past the POL erroring out.
was told we need Lee to give us a hand at the situation.
Party included Dimes, Crank, Crunk, Crowne, Jupiterjones and Cord(who doesnt need)

**Comment by Leelink1** [comment]
Yea its a known issue with DSP. Usually if you manage to beat the fight i allow credit to all the members. Same issue with CoP 8-4

**Comment by dwn134** [comment]
The last 2 of us got killed in the cs from ultima before it was done

**Comment by dwn134** [comment]
Know dsp problem same as 8-4
