### ISSUE TITLE
DRG probelmes :O

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#58]
Hello everyone,

I going to list some issus with drg.

1st. When Master use Super jump the pet donst use Super Climb [http://ffxiclopedia.wikia.com/wiki/Super_Climb](url).

2nd. Spirit Link Use 50% of master HP to heal pet which should be around 25%-35% of user's current HP. The amount drained is random. [http://ffxiclopedia.wikia.com/wiki/Spirit_Link](url)

3rd. DRG pet hHP is much lover then master i think he dont get signet bonus like master. With red hp just 1% and with yellow or white HP just 2% 

Thanks for the hard work and keep up the good work.

**Comment by GMYasiinEra** [comment]
Pets DEF has been increased by 40% and the 2hr has been fixed.. superclimb still isnt coded i dont think but could be closed for now,
