### ISSUE TITLE
Holidays and shop closing times

### ISSUE THREAD

**Issue by dwn134** [myera/issues#6]
could we abolish this closed times? i remember when i first started playing era that the shops were always open. Nothing like wasting an hour or more waiting to get an item just because it wont sell to you at this time

**Comment by Scavenge** [comment]
the more stuff we change the more upkeep we have to do, and in the span of the darkstar project that's not really a priority.  i'm not saying no, but i don't really favor it because it causes more detachment from DSP and less progress toward accurately working guilds
