### ISSUE TITLE
Carby Healing Ruby Issue

### ISSUE THREAD

**Issue by Beakahn** [myera/issues#60]
Carbuncle's Healing Ruby is supposed to do a single heal on any selected party member. Manually casting brings up the blue arrow over a party member, but upon cast, Carbuncle always heals the SMN. Yushiro has ver
![carby heal](https://cloud.githubusercontent.com/assets/18542828/14625444/0f696024-05b1-11e6-9d96-edca159ec58e.PNG)
ified.

**Comment by dwn134** [comment]
ticket #9, its the same thing ive submitted awhile back

**Comment by Beakahn** [comment]
Yushiro was with me and asked me to submit, so I did.

**Comment by GM-Dave** [comment]
The Bloodpact should currently be working as intended. If it isn't please file a new ticket.
