### ISSUE TITLE
Perfect Dodge Matrix style

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#61]
Hello everyone,

When Perfect Dodge is used u cant hit it with rng atts.

> With blazing agile movements, this secret technique allows the Thief to disrupt the enemy and completely avoid all physical melee attacks. However, this ability cannot dodge ranged attacks or magic. 

http://ffxiclopedia.wikia.com/wiki/Perfect_Dodge?oldid=917033

**Comment by GM-Dave** [comment]
Perfect Dodge should currently be working as intended. Any new issues that may occur should please be filed under a new ticket.
