### ISSUE TITLE
Flume Toads in Toraimarai Canal are now undead

### ISSUE THREAD

**Issue by bigcarl35** [myera/issues#62]
I was in Toraimarai Canal today to farm Magical Hammer off the Flume Toads there when I discovered that the "toads" were now undead.  (See attached ss.)  Thought it might be a visual bug, so I fought a couple.  They use strictly undead tp moves.  I was in this area before when I was on my way to do the Fenrir fight a couple of weeks ago.  They were toads when I passed them then.

![Uploading img_20160422_222751.png…]()

**Comment by GM-Dave** [comment]
Toads should now use their correct TP moves. If this is an issue again please file a new ticket.
