### ISSUE TITLE
 I can not log into my character

### ISSUE THREAD

**Issue by Ablonn** [myera/issues#63]
I use Windower to enter the game.

When I open, load the input video everything right.
I select my character and give "ok" to login with it normally.
The screen goes black for about a minute, with the words "donwloading data" appearing at the bottom with the animation and simply appears blue rectangle error, accusing the FFXI-3001 error "No response from the FINAL FANTASY XI server. Connection timed out. press OK to shut down.
I do not know if it's here that I do this measured help, but I've tried restarting the PC and everything and nothing work fot.

I apologize if it is not here the right place to ask for that help.

The name of my Acc is "Shran" having a character named "Ablon" which has BLM and SAM 75.
Thank you very much in advance.

Kind regards.
Ablon.

**Comment by Scavenge** [comment]
this section for reporting is depersonalized and meant for gameplay bugs, you may want to try posting your issue in the 'service requests' area of reporting if you haven't already

**Comment by Scavenge** [comment]
that being said, this may be due to a few things, could be that you updated recently, or could be ongoing issues with our login server or there is a small chance it's because your character is needing a gm reset.  my money is on you updating recently.
