### ISSUE TITLE
Quivering arrows/bolts randomly crashes client

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#67]
Trading arrows or bolts and the carnations needed to Nokkhi Jinjahl sometimes works with the right chatlog message, sometimes with the wrong message ("target item must be equipped") and about 80% of the time it results in a xiloader crash. I have tried this with bolts, various arrows and different numbers of stacks traded, but have not found any consistency. Most of the time it will crash, sometimes it won't. Quivered items will be in the inventory upon relogging, so there is no item loss.

**Comment by Aerixaa** [comment]
Can coffrim that happens to me to.

**Comment by GM-Dave** [comment]
#264

Newer ticket tracking this issue
