### ISSUE TITLE
Elshimo Newt

### ISSUE THREAD

**Issue by dwn134** [myera/issues#7]
http://ffxiclopedia.wikia.com/wiki/Elshimo_Newt

this item is currently not buy-able or obtainable in anyway. Wiki says you could buy it from guild but it not there and currently fishing is dead, could it be added to an npc.
tring to make goblin drink to pop for parade gorget

goblin drink - http://ffxiclopedia.wikia.com/wiki/Goblin_Drink
nm - http://ffxiclopedia.wikia.com/wiki/Goblin_Wolfman

**Comment by Leelink1** [comment]
Obtainable on the mobs.

**Comment by dwn134** [comment]
can close the ticket, farmed the fish
