### ISSUE TITLE
Dolls in Ro'Maeve Aggro Sight

### ISSUE THREAD

**Issue by Brooster** [myera/issues#70]
The dolls in ro'maeve aggro sight. just to be clear they do not aggro true sight since i tested it with having inv on and then dropping it.

**Comment by Darkstorm87** [comment]
Brooster,

If this server is running off DSP database values in this specific instance, I believe the necessary change will need to happen on this database record.
```
INSERT INTO `mob_family_system` VALUES (85,'Doll',3,'Arcana',1,40,108,90,1,3,4,3,6,6,5,3,3,3,3,1,1,1,1,1,1,1,1,1.25,1,1,1,2,33,0);
```

This wiki page describes the correct behavior of this mob:
[http://ffxiclopedia.wikia.com/wiki/Cursed_Puppet](http://ffxiclopedia.wikia.com/wiki/Cursed_Puppet)

_**I believe that the "detects" field needs to be updated and changed from 33 to 32.**_

As defined by the detect enum in mobentity.h:

```
enum DETECT : uint16
{
    DETECT_NONE        = 0x00,
    DETECT_SIGHT       = 0x01,
    DETECT_HEARING     = 0x02,
    DETECT_LOWHP       = 0x04,
    DETECT_NONE1       = 0x08,
    DETECT_NONE2       = 0x10,
    DETECT_MAGIC       = 0x20,
    DETECT_WEAPONSKILL = 0x40,
    DETECT_JOBABILITY  = 0x80,
    DETECT_SCENT       = 0x100
};
```

Magic aggro is 32 = 0x20 = 0010 0000
Sight aggro is 1 = 0x01 = 0000 0001

in this case the value 33 in the database would represent: 33 = 0x21 = 0010 0001

When doing a PMob->m_Detects & DETECT_SIGHT within the Core code, this would allow the dolls to aggro via sight.

One caveat to this change is that the following record will not longer be valid:

```
INSERT INTO `mob_pools` VALUES (203,'Apollyon_Sweeper',85,0x0000300100000000000000000000000000000000,1,1,12,240,100,0,1,1,1,2,0,0,4680,1159,0,0,0,1,0,85);
```
Apollyon Sweeper according to the following link CAN aggro sight and infact aggro's true sight.
http://ffxiclopedia.wikia.com/wiki/Apollyon_Sweeper

The Apollyon Sweeper will need to be moved under the correct mob family for that mob to behave accurately.

**Comment by Locodawg** [comment]
This has been resolved.
