### ISSUE TITLE
Gravity evasion down effect

### ISSUE THREAD

**Issue by Darkstorm87** [myera/issues#72]
http://forum.square-enix.com/ffxi/threads/43135-Jul-8-2014-%28JST%29-Version-Update?highlight=Distract

In this version update they describe that retail gravity lost it's evasion down effect.  If Era is trying to represent the 75 cap time frame, we might want to add that evasion down effect back to gravity.  I believe it was 5%, but capped at -10 evasion

http://ffxiclopedia.wikia.com/index.php?title=Gravity&diff=1493115&oldid=1360353

**Comment by Aerixaa** [comment]
Cant we just get this spell http://ffxiclopedia.wikia.com/wiki/Distract? In place of gravity if it to strong make it weaker.

**Comment by Darkstorm87** [comment]
looks like onEffectGain of weight lowers evasion

`function onEffectGain(target,effect)
    if (effect:getPower()>100) then
        effect:setPower(50);
    end
    target:addMod(MOD_MOVE,-effect:getPower());
    target:addMod(MOD_EVA,-effect:getPower()/5);
end;
`

Can a dev confirm that scripts\globals\effects\weight.lua on Era is doing this?  Should be able to close this as a non-issue if so, and my bad.
