### ISSUE TITLE
Missing desynth for Wivre hairpin

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#73]
I noticed that Wivre hairpin (Bonecraft 85) is synthable but not desynthable.
http://ffxiclopedia.wikia.com/wiki/Wivre_Hairpin

Would be much appreciated if it could be added any time when convenient :)

Keep up the good work! \(^_^)/

**Comment by dwn134** [comment]
???,0,0,0,85,0,0,0,0,0,0,4100,4242,16128,0,0,0,0,0,0,0,2427,2427,2427,2427,1,1,1,1

woot woot think i did it correctly

**Comment by MarkWaldron** [comment]
https://github.com/DarkstarProject/darkstar/pull/3192
