### ISSUE TITLE
Making the Grade Quest

### ISSUE THREAD

**Issue by Tacien** [myera/issues#79]
Finished the quest for a scroll of Aspir (Making the Grade quest in Windurst Waters) and did not receive the scroll upon completion. Attaching a photo of the completion convo in the chat log. 
![img_20160506_220759](https://cloud.githubusercontent.com/assets/18506829/15089961/a9167f02-13d7-11e6-8534-167392a1cb56.png)

**Comment by Rihce** [comment]
gave scroll. issue seems to be waiting on DSP to fix on finish events
