### ISSUE TITLE
 Tebhi PLD AF2 quest line.

### ISSUE THREAD

**Issue by goatfinger** [myera/issues#80]
The custom quest line for PLD AF2 works all the way up to trading the NPC Tebhi. Will not accept Giant shell bug via trade.

**Comment by GM-Dave** [comment]
This was unfortunately never repaired once it broke because of an update. (the normal questline via retail standard doesnt work because of limitations to fishing on DSP/Era.) A work around is in place currently that you can get PLD AF drops (including feet & body) from Pugils in Mount Zhayolm.
