### ISSUE TITLE
BCNM "Like the Wind" broken

### ISSUE THREAD

**Issue by FleabittenGrey** [myera/issues#81]
Completing BCNM "Like the Wind" results in being sent into an infinite loop of teleporting back to the beginning over and over.   https://gyazo.com/b730a0ecd66ee0034f74550fbe13cffb and https://gyazo.com/02e80fbf17fe48143570b105bb84f512.  also continuously drops  you to r0 and then back.  had to force close.

**Comment by Locodawg** [comment]
This has been resolved.
