### ISSUE TITLE
Boat from Whitegate to Nashmau

### ISSUE THREAD

**Issue by hambyzor** [myera/issues#82]
Hey guys, I've been trying to travel by boat from Aht Urghan Whitegate to Nashmau and after traveling for about 30 minutes on the boat, it never reached its destination. I had to warp off.

**Comment by Rihce** [comment]
sadly its a known issue with all boats/airships. you sadly have a 50/50 chance of this bug happening. just keep trying the boat ride till it works.

**Comment by GM-Dave** [comment]
The boat WG to Nashmau should work, though the trip is known to take extra time compared to what it should. Highly recommended to either use alternative methods for getting to Nashmau and/or grabbign the homepoint in the zone for future use once there.
