### ISSUE TITLE
summoner can have multiple pets out at once

### ISSUE THREAD

**Issue by opivylint** [myera/issues#83]
summoner can summon as many pets as they want with the exclusion of carbuncle works on every other u can only issue a command to the most recently summoned and the most recently summoned is also the only 1 with perpetuation cost so for example I can summon ifrit > assault > summon ifrit > assault > summon ifrit > assault etc..... or any prime avatar at 1 pont I had at least 4 avatars engaged to the same target and have had as many as 10+ out at once issue just started as of today 5-10-16
![img_20160510_145718](https://cloud.githubusercontent.com/assets/19241007/15159088/bf01a184-16c0-11e6-8720-a6b2d085f1ef.png)
![img_20160510_145713](https://cloud.githubusercontent.com/assets/19241007/15159091/c0e03f60-16c0-11e6-8944-32d28f07ba60.png)
![img_20160510_145710](https://cloud.githubusercontent.com/assets/19241007/15159093/c2d5a0da-16c0-11e6-9bd4-a8ec8983d0f4.png)
![img_20160510_144719](https://cloud.githubusercontent.com/assets/19241007/15159097/c42877fa-16c0-11e6-9e9f-26430368ace2.png)
![img_20160510_143909](https://cloud.githubusercontent.com/assets/19241007/15159098/c6082da4-16c0-11e6-856c-21740cb7551d.png)
![img_20160510_143741](https://cloud.githubusercontent.com/assets/19241007/15159099/c7ab5032-16c0-11e6-8962-6955662c6e01.png)

**Comment by eraffxi** [comment]
fixed
