### ISSUE TITLE
King Vinegarroon Additional effect: Petrification Issue (100% rate)

### ISSUE THREAD

**Issue by Sanlord** [myera/issues#84]
![img_20160510_210651](https://cloud.githubusercontent.com/assets/15907792/15166478/a23a062e-16f5-11e6-8a88-b326081a945b.png)

The image says it all.

**Comment by Darkstorm87** [comment]
http://ffxiclopedia.wikia.com/wiki/King_Vinegarroon

What do you want him to be like?  He's **_supposed_** to have petrification on all of his attacks.

**Comment by Sanlord** [comment]
This was never supposed to be 100%, i'm 100% sure about it.

**Comment by Darkstorm87** [comment]
Did this get fixed or did you just close it?  Try to go find some evidence that backs this up.

I've been looking at old video's and youtube is littered with video's with mage's that filtered out KV's attacks...  I did find a few that supports your claim.

https://www.youtube.com/watch?v=bgIUhq0LGVA
https://www.youtube.com/watch?v=Pjz-krhyGKQ

They are lvl99 fights, so things may have changed... but it clearly shows a proc rate that is less than 100%.  The ffxiclopedia page may have a misleading verbiage.
