### ISSUE TITLE
Bind Sleep hate reset

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#85]
When ever u Bind or sleep a mob and run out sight, after bind or sleep wear u love hate mob goes from Red name to green name and start healing mp and runing bk to his place. This is kinda Huge problem because like this u cant Kite nuke etc. I showed it to Yushiro on  Vanguard Dragon. THis bug is not only in many place. U can easy Lullpy stuff run away and lose hate and rest of pt pull the 1 mob u need. Btw this go for any kind for blm or brd didnt try blu

**Comment by GM-Dave** [comment]
This issue has been mostly resolved, though a player can still lose hate/claim by running to far way from the mob.
