### ISSUE TITLE
All Pets JObs and Pet problem

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#87]
Call Pet from BST stay alife and fight even when Master is death

**Comment by Aerixaa** [comment]
Looks like same happens to avatars and smn to http://i.imgur.com/1RquKlv.jpg

**Comment by Shahuaforthewin** [comment]
Also noticed "Sic" is gone.
This confused me.

**Comment by Aerixaa** [comment]
Also happend with drg and drg pet master death and pet stay and keep fighting till hp down to 0

**Comment by GM-Dave** [comment]
These issues have been repaired with a recent update. If they return please file a new ticket.
