### ISSUE TITLE
Gardening not working

### ISSUE THREAD

**Issue by kalkulator102** [myera/issues#91]
Nothing happens when trying to plant seeds.

Seeds tested: Vegatable Seeds, Grain Seeds, Herb Seeds
Flowerpots tested: Ceramic Flowerpot, Brass Flowerpot

http://i.imgur.com/8Eyhuev.png

**Comment by Aerixaa** [comment]
i think that just not coded

**Comment by Rihce** [comment]
correct it isn't coded

**Comment by Locodawg** [comment]
Officially Gardening has not been coded by DSP as of yet.
