### ISSUE TITLE
Sea issus

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#92]
Sea very buggy atm 
JoH way to OP on retail we did him with BRD NIN THF RDM. Tryed sam Setup here no way even with 457 eva on Ninja get hit like 100% like he hase 100% acc and JoH hase like Hunderfrist his attack speed it was to fast even with brd slow and slow 2 from rdm -.-. 

Aern Mobs way to strong also 100% acc and 100% double attack >:>. VT Aern way to OP. 6man on VT Aern dieing is so damm wrong -.-. I dont even want to all Ix aern NMs. If normal Mobs are already that hard.

Will add more if i find more

**Comment by eraffxi** [comment]
mnk based mobs are currently broken strong and it's being worked on

**Comment by GM-Dave** [comment]
Sea NMs & Jailers have been repaired to be nearly 100% functional (with the exception of AV). Multi attack trait procs on mobs has also been adjusted to be more reasonable.
