### ISSUE TITLE
BLU Learning

### ISSUE THREAD

**Issue by Noscot** [myera/issues#93]
My BLU seems to be unable to learn spells.
i tryed for Maelstrom and Regeneration from Devil Manta in Sea seropent Grotto and
Self-Destruct - Volcanic Bomb, Radiant Breath - Hurricane Wyvern, Infrasonics - Ash Lizards in Ifrits Caulderon.

BLU skill @ 291 with BLU Hands equip all time, killed a lot of them while farming didnt get 1 of the spells.

**Comment by Shahuaforthewin** [comment]
I too have been having the problem as I need to collect spells for my BLU Limitbreak fight.

I managed to learn "Ice Break" and "Smite of Rage" since update But nothing else.
Been killing tons of monsters.

**Comment by eraffxi** [comment]
fixed
