### ISSUE TITLE
Shikigami Weapon AI

### ISSUE THREAD

**Issue by DeeJayMhyst** [myera/issues#97]
Shiki is on roam, sight agro and visible. Should be roam (optional?), invisible and magic agro.

**Comment by Aerixaa** [comment]
That was always like that i think never was code differnet

**Comment by DeeJayMhyst** [comment]
Nah. It was set to sit there and would not agro except magic. Then it was set to roam, but still only magic agro. Then it was put invisible.

**Comment by Brooster** [comment]
yes, shikigami weapon is supposed to roam but is supposed to be invisible and magic aggro only. he now roams visible and aggros when he runs by you. not sure if its sight or sound. but he just rocked my world. just giving you a +1 to the ticket

**Comment by Locodawg** [comment]
This has been resolved.
