### ISSUE TITLE
Monk Permanent Hundred Fists

### ISSUE THREAD

**Issue by Taladric** [myera/issues#98]
Logged in to find that my monk doesn't stop attacking... permanent Hundred Fists effect.  Zoned, changed jobs, relogged and still has effect.  Continued to keep effect for over 2 hours.

**Comment by Aerixaa** [comment]
I think it because us maybe Hades Sainti. It more like Hades Sainti make u 0 delay

**Comment by Shahuaforthewin** [comment]
I noticed this, however only happened when I equip hades santi @ Level 70.
Before then my mnk just hit normal.

**Comment by Sanlord** [comment]
Happenned with Retaliators aswell.

**Comment by Aerixaa** [comment]
Happens to all weapons try it with Relic and cresti same

**Comment by Shahuaforthewin** [comment]
Looks like it's fixed

**Comment by eraffxi** [comment]
fixed on players
