### ISSUE TITLE
Crash related to summoner Bloodpact

### ISSUE THREAD

**Issue by Myronnis** [myera/issues#99]
As I was doing Fenrir's Bloodpact Ward Lunar Cry, the colibri landed a hit on Fenrir and it died, so he started despawning and my game instantly froze and crashed, not sure if I can repeat that or just a coincidence, or even if it's DS programming problems, but just reporting in case!

**Comment by Aerixaa** [comment]
happend to me to with POsion nail looks like it /random

**Comment by GM-Dave** [comment]
This was an issue with using bloodpacts on mobs/targets that died/despawned. a recent update seems to have fixed this issue.
